<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Plant\PipingNode.fs" />
        <Compile Include="Plant\Nozzle.fs" />
        <Compile Include="Plant\Piping.fs" />
        <Compile Include="Plant\Equipment.fs" />
        <Compile Include="Plant\TaggedPlantItem.fs" />
        <Compile Include="Plant.fs" />
    </ItemGroup>

</Project>
