// <auto-generated>
// DEXPI 2.0 UML model -> C++ - flattened conversion by Dexpi2CppFlatten (rule version 1.0).
// Source: dexpi2.hpp (SHA-256: e81ff83c9093ec5e8464c61cfaff00cbf74b303f7da45423de0d19e3204b9f67)
// Aggregate header: includes every top-level namespace file in dependency order.
// Include this file to get the whole flat DEXPI 2.0 model.
// </auto-generated>
#pragma once
#include "dexpi2_core.hpp"
#include "dexpi2_auxiliaries.hpp"
#include "dexpi2_plant.hpp"
#include "dexpi2_process.hpp"

