// 生成 FSharp.DEXPI2/Plant/TaggedPlantItemUnion.fs
// 用法：dotnet fsi FSharp.DEXPI2/tools/generate-tagged-plant-item-union.fsx
open System
open System.IO
open System.Text
open System.Text.RegularExpressions

let toolsDir = __SOURCE_DIRECTORY__
let fsProjectDir = Directory.GetParent(toolsDir).FullName // FSharp.DEXPI2
let repoRoot = Directory.GetParent(fsProjectDir).FullName // 仓库根
let inDir = Path.Combine(repoRoot, "Dexpi2.CSharp.Generator", "input")
let outFile = Path.Combine(fsProjectDir, "Plant", "TaggedPlantItemUnion.fs")

let nsRe = Regex(@"^namespace\s+(\w+)\s*\{\s*$")
let nsCloseRe = Regex(@"^\}\s*//\s*namespace\s+(\w+)\s*$")
let classRe =
    Regex(@"// DEXPI 2\.0 model class\s+(?<doc>.+?)\s*\(XMI id (?<xmi>ID\d+)\)(?<rest>[^\n]*)\n\s*class\s+(?<name>\w+)\s*\{\s*(?<body>.*?)\s*\};",
          RegexOptions.Singleline)

type ClassDecl =
    { Ns: string list
      Name: string
      Abstract: bool
      Bases: string list }

let parseFile (path: string) : ClassDecl list =
    let text = (File.ReadAllText path).Replace("\r\n", "\n").Replace('\r', '\n')
    let lines = text.Split('\n')
    let nsAt = Array.create lines.Length []
    let stack = System.Collections.Generic.List<string>()
    for li in 0 .. lines.Length - 1 do
        // List.Add 为尾插：stack 已是 [最外层; ...; 最内层]，无需反转
        nsAt.[li] <- stack |> Seq.toList
        let m = nsRe.Match lines.[li]
        if m.Success then
            stack.Add(m.Groups.[1].Value)
        else
            let c = nsCloseRe.Match lines.[li]
            if c.Success && stack.Count > 0 then stack.RemoveAt(stack.Count - 1)
    [ for m in classRe.Matches text ->
        let rest = m.Groups.["rest"].Value
        let startLine = text.Substring(0, m.Index).Split('\n').Length - 1
        { Ns = nsAt.[startLine]
          Name = m.Groups.["name"].Value
          Abstract = rest.Contains("[abstract in DEXPI]")
          Bases =
            let bm = Regex.Match(rest, @"bases inlined: ([^\]]+)")
            if bm.Success then
                bm.Groups.[1].Value.Split(',')
                |> Array.map (fun s -> s.Trim())
                |> Array.filter (fun s -> s <> "")
                |> Array.toList
            else [] } ]

let capitalize (s: string) =
    if s.Length = 0 then s else string (Char.ToUpperInvariant s.[0]) + s.Substring(1)

// 与 C# 生成器保持一致：过滤 dexpi2 段后显式加 "Dexpi2." 前缀
let csNamespace (ns: string list) : string =
    let segments = ns |> List.filter (fun s -> s <> "dexpi2") |> List.map capitalize
    if segments.IsEmpty then "Dexpi2" else "Dexpi2." + String.concat "." segments

let headers =
    [ "dexpi2_core.hpp"; "dexpi2_auxiliaries.hpp"; "dexpi2_plant.hpp"; "dexpi2_process.hpp" ]

let allClasses =
    headers
    |> List.collect (fun h -> parseFile (Path.Combine(inDir, h)))

// 基类名全局唯一性检查（重名会导致继承推导歧义）
let dup =
    allClasses
    |> List.groupBy (fun c -> c.Name)
    |> List.filter (fun (_, g) ->
        g |> List.map (fun c -> csNamespace c.Ns) |> Set.ofList |> Set.count > 1)
if not dup.IsEmpty then
    failwithf "ambiguous class names: %A" (dup |> List.map fst)

let classByName = allClasses |> List.map (fun c -> c.Name, c) |> Map.ofList

// children：名字 -> 以它为直系基类的类
let children = System.Collections.Generic.Dictionary<string, ResizeArray<ClassDecl>>()
for c in allClasses do
    for b in c.Bases do
        if not (classByName.ContainsKey b) then
            failwithf "unknown base '%s' of %s" b c.Name
        let l =
            match children.TryGetValue b with
            | true, l -> l
            | _ ->
                let l = ResizeArray<ClassDecl>()
                children.[b] <- l
                l
        l.Add c

let target = "TaggedPlantItem"
let targetDecl = classByName.[target]
let targetCsNs = csNamespace targetDecl.Ns

// 传递闭包：全部派生类（含中间非叶类）
let seen = System.Collections.Generic.HashSet<string>()
let found = ResizeArray<ClassDecl>()
let rec walk (name: string) =
    match children.TryGetValue name with
    | true, list ->
        for child in list do
            if seen.Add child.Name then
                found.Add child
                walk child.Name
    | _ -> ()
walk target

let desc =
    found
    |> Seq.filter (fun c -> not c.Abstract)
    |> Seq.sortBy (fun c -> csNamespace c.Ns + "." + c.Name)
    |> Seq.toList

let refName (c: ClassDecl) : string =
    if csNamespace c.Ns = targetCsNs then c.Name else csNamespace c.Ns + "." + c.Name

let sb = StringBuilder()
let app (s: string) = sb.Append(s).Append("\r\n") |> ignore
app "// <auto-generated>"
app "// 可区分联合：Dexpi2.Plant.Processequipment.TaggedPlantItem 的所有非抽象派生类型（含非叶类）。"
app "// 每个案例荷载对应的 C# 类型（System.Type），类型来自 Dexpi2.CSharp 程序集。"
app "// 生成方式：dotnet fsi FSharp.DEXPI2/tools/generate-tagged-plant-item-union.fsx"
app "// 数据来源：Dexpi2.CSharp.Generator/input/*.hpp 中 \"[flattened; bases inlined: ...]\" 直系基类注释。"
app "// </auto-generated>"
app ""
app "namespace FSharp.DEXPI2.Plant.ProcessEquipment"
app ""
app "open System"
app (sprintf "open %s" targetCsNs)
app ""
app "/// <summary>可区分联合：TaggedPlantItem 的所有非抽象派生类型（含非叶类）。每个案例荷载对应的 C# 类型。</summary>"
app "type TaggedPlantItemUnion ="
for c in desc do
    app (sprintf "    | %sCase of Type" c.Name)
app ""
app "    /// <summary>全部案例（含非叶类），按 C# 类型全名排序。</summary>"
app "    static member All : TaggedPlantItemUnion list ="
app (sprintf "        [ %sCase typeof<%s>" desc.Head.Name (refName desc.Head))
for c in desc.Tail do
    app (sprintf "          %sCase typeof<%s>" c.Name (refName c))
app "          ]"

File.WriteAllText(outFile, sb.ToString(), UTF8Encoding(true))
printfn "wrote %s (%d cases)" outFile desc.Length
