<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ProcessEquipment.fs" />
    <Compile Include="PipingNodeOwner.fs" />
    <Compile Include="PipingNetworkSegment.fs" />
    <Compile Include="PipingNetworkSystem.fs" />
    <Compile Include="PlantModel.fs" />
  </ItemGroup>

</Project>
