<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DEXPI2.Test</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="InPlaceTree.fs" />
    <Compile Include="PumpTree.fs" />
    <Compile Include="TeeTree.fs" />
    <Compile Include="SensorwellTree.fs" />
    <Compile Include="Reference47121.fs" />
    <Compile Include="Reference47122.fs" />
    <Compile Include="Reference47123.fs" />
    <Compile Include="Reference47124.fs" />
    <Compile Include="Reference47125.fs" />
    <Compile Include="Reference47126.fs" />
    <Compile Include="Reference47127.fs" />
    <Compile Include="Reference47130.fs" />
    <Compile Include="Reference47131.fs" />
    <Compile Include="Reference47140.fs" />
    <Compile Include="Reference47141.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="10.1.401" />
    <PackageReference Include="xunit.v3.assert" Version="4.0.1" />
    <PackageReference Include="xunit.v3.core.mtp-v2" Version="4.0.1" />
    <PackageReference Include="FSharp.xUnit" Version="1.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DEXPI2\DEXPI2.fsproj" />
  </ItemGroup>

</Project>
