// <auto-generated>
// DEXPI 2.0 UML model -> C++ - flattened conversion by Dexpi2CppFlatten (rule version 1.0).
// Source: dexpi2.hpp (SHA-256: e81ff83c9093ec5e8464c61cfaff00cbf74b303f7da45423de0d19e3204b9f67)
// Abstract/concrete base classes are FULLY INLINED into every derived class (flat hierarchy):
//   - no class inherits from anything; every class is self-contained
//   - abstract classes remain as reference types, still marked [abstract in DEXPI]
//   - C++ shadowing: a derived member with the same name as an inherited one wins
// Top-level namespace: dexpi2::core
// </auto-generated>
#pragma once

#include <memory>
#include <optional>
#include <string>
#include <vector>


// Forward declarations for every model class in this file (std::shared_ptr members accept incomplete types).
namespace dexpi2 {
namespace core {
    class ConceptualObject;
    class EngineeringModel;
    class PersistentIdentifier;
    class Role;
    class ConceptualModel;
    class Note;
    class QualifiedValue;
} // namespace core
namespace core {
namespace datatypes {
    class MultiLanguageString;
    class SingleLanguageString;
} // namespace datatypes
} // namespace core
namespace core {
namespace diagram {
    class Color;
    class GraphicalElement;
    class GraphicsGroup;
    class NodePosition;
    class Point;
    class Shape;
    class ShapeCatalogue;
    class Stroke;
    class TextTemplate;
    class TextTemplateFragment;
    class MetaData;
    class GraphicalPrimitive;
    class ShapeUsage;
    class RepresentationGroup;
    class RepresentationTypeGroup;
    class AttributeRepresentation;
    class LiteralText;
    class ConnectorLine;
    class Ellipse;
    class EllipseArc;
    class PolyLine;
    class Polygon;
    class Text;
    class Diagram;
    class Border;
    class Label;
    class Static;
    class Symbol;
    class CustomSymbol;
    class InsulationSymbol;
    class PipeFlowArrow;
    class PipeSlopeSymbol;
} // namespace diagram
} // namespace core
namespace core {
namespace physicalquantities {
    class PhysicalQuantity;
    class PhysicalQuantityUnit;
    class PhysicalQuantityVector;
    class FrequencyUnit;
    class PressureUnit;
} // namespace physicalquantities
} // namespace core
} // namespace dexpi2

namespace dexpi2 {

namespace core {
namespace datatypes {
    // DEXPI 2.0 enumeration QuantityProvenance (XMI id ID38)
    enum class QuantityProvenance
    {
        Calculated,  // Calculated
        Estimated,  // Estimated
        Observed,  // Observed
        Set,  // Set
        Specified,  // Specified
    };
    // DEXPI 2.0 enumeration QuantityRange (XMI id ID44)
    enum class QuantityRange
    {
        Actual,  // Actual
        Average,  // Average
        LowerLimit,  // LowerLimit
        Nominal,  // Nominal
        Normal,  // Normal
        UpperLimit,  // UpperLimit
    };
    // DEXPI 2.0 enumeration Scope (XMI id ID51)
    enum class Scope
    {
        Alarm,  // Alarm
        Allowable,  // Allowable
        Design,  // Design
        Expected,  // Expected
        Incidental,  // Incidental
        Operating,  // Operating
        Protection,  // Protection
        Rated,  // Rated
        Test,  // Test
        Warning,  // Warning
    };
} // namespace datatypes
} // namespace core

namespace core {
namespace diagram {
    // DEXPI 2.0 enumeration AttributeRepresentationType (XMI id ID73)
    enum class AttributeRepresentationType
    {
        Units,  // Units
        Value,  // Value
        ValueAndUnits,  // ValueAndUnits
    };
    // DEXPI 2.0 enumeration ConfidentialityClassification (XMI id ID83)
    enum class ConfidentialityClassification
    {
        ConfidentialInformation,  // ConfidentialInformation
        NonConfidentialInformation,  // NonConfidentialInformation
    };
    // DEXPI 2.0 enumeration DashStyle (XMI id ID101)
    enum class DashStyle
    {
        Dash,  // Dash
        DashShortDash,  // DashShortDash
        Dot,  // Dot
        LongDash,  // LongDash
        LongDashShortDash,  // LongDashShortDash
        LongDashShortDashShortDash,  // LongDashShortDashShortDash
        ShortDash,  // ShortDash
        Solid,  // Solid
    };
    // DEXPI 2.0 enumeration FillStyle (XMI id ID121)
    enum class FillStyle
    {
        Hatch,  // Hatch
        Solid,  // Solid
        Transparent,  // Transparent
    };
    // DEXPI 2.0 enumeration TextAlignment (XMI id ID227)
    enum class TextAlignment
    {
        CenterBottom,  // CenterBottom
        CenterCenter,  // CenterCenter
        CenterTop,  // CenterTop
        LeftBottom,  // LeftBottom
        LeftCenter,  // LeftCenter
        LeftTop,  // LeftTop
        RightBottom,  // RightBottom
        RightCenter,  // RightCenter
        RightTop,  // RightTop
    };
} // namespace diagram
} // namespace core

namespace core {
namespace physicalquantities {
    // DEXPI 2.0 enumeration AreaUnit (XMI id ID272)
    enum class AreaUnit
    {
        CentimetreSquared,  // CentimetreSquared
        FootSquared,  // FootSquared
        InchSquared,  // InchSquared
        MetreSquared,  // MetreSquared
        MillimetreSquared,  // MillimetreSquared
        YardSquared,  // YardSquared
    };
    // DEXPI 2.0 enumeration DensityUnit (XMI id ID280)
    enum class DensityUnit
    {
        KilogramPerLitre,  // KilogramPerLitre
        KilogramPerMetreCubed,  // KilogramPerMetreCubed
        PoundMassPerFootCubed,  // PoundMassPerFootCubed
        PoundMassPerUsGallon,  // PoundMassPerUsGallon
    };
    // DEXPI 2.0 enumeration DynamicViscosityUnit (XMI id ID285)
    enum class DynamicViscosityUnit
    {
        Centipoise,  // Centipoise
        MillipascalSecond,  // MillipascalSecond
        PascalSecond,  // PascalSecond
        Poise,  // Poise
    };
    // DEXPI 2.0 enumeration ElectricCurrentUnit (XMI id ID290)
    enum class ElectricCurrentUnit
    {
        Ampere,  // Ampere
        Kiloampere,  // Kiloampere
        Milliampere,  // Milliampere
    };
    // DEXPI 2.0 enumeration ElectricalFrequencyUnit (XMI id ID294)
    enum class ElectricalFrequencyUnit
    {
        Hertz,  // Hertz
        KiloHertz,  // KiloHertz
        MegaHertz,  // MegaHertz
    };
    // DEXPI 2.0 enumeration EnergyDensityUnit (XMI id ID299)
    enum class EnergyDensityUnit
    {
        JoulePerCubicMetre,  // JoulePerCubicMetre
        KilojoulePerCubicMetre,  // KilojoulePerCubicMetre
    };
    // DEXPI 2.0 enumeration EnergyUnit (XMI id ID302)
    enum class EnergyUnit
    {
        Joule,  // Joule
        Kilojoule,  // Kilojoule
        KilowattHour,  // KilowattHour
        Megajoule,  // Megajoule
        MegawattHour,  // MegawattHour
    };
    // DEXPI 2.0 enumeration ForceUnit (XMI id ID308)
    enum class ForceUnit
    {
        KiloNewton,  // KiloNewton
        Newton,  // Newton
    };
    // DEXPI 2.0 enumeration HeatCapacityUnit (XMI id ID311)
    enum class HeatCapacityUnit
    {
        BtuITPerDegreeFahrenheit,  // BtuITPerDegreeFahrenheit
        BtuThPerDegreeFahrenheit,  // BtuThPerDegreeFahrenheit
        WattPerKelvin,  // WattPerKelvin
    };
    // DEXPI 2.0 enumeration HeatTransferCoefficientUnit (XMI id ID315)
    enum class HeatTransferCoefficientUnit
    {
        KilowattPerMetreSquaredKelvin,  // KilowattPerMetreSquaredKelvin
        WattPerMetreSquaredKelvin,  // WattPerMetreSquaredKelvin
    };
    // DEXPI 2.0 enumeration HeatTransferResistanceUnit (XMI id ID318)
    enum class HeatTransferResistanceUnit
    {
        FootSquaredHourDegreeFahrenheitPerBtuTh,  // FootSquaredHourDegreeFahrenheitPerBtuTh
        MetreSquaredKelvinPerWatt,  // MetreSquaredKelvinPerWatt
    };
    // DEXPI 2.0 enumeration KinematicViscosityUnit (XMI id ID321)
    enum class KinematicViscosityUnit
    {
        CentimetreSquaredPerSecond,  // CentimetreSquaredPerSecond
        Centistoke,  // Centistoke
        MetreSquaredPerSecond,  // MetreSquaredPerSecond
        Stoke,  // Stoke
    };
    // DEXPI 2.0 enumeration LengthUnit (XMI id ID326)
    enum class LengthUnit
    {
        Centimetre,  // Centimetre
        Foot,  // Foot
        Inch,  // Inch
        Kilometre,  // Kilometre
        Metre,  // Metre
        Micrometre,  // Micrometre
        Millimetre,  // Millimetre
        Nanometre,  // Nanometre
    };
    // DEXPI 2.0 enumeration MagneticFieldIntensityUnit (XMI id ID335)
    enum class MagneticFieldIntensityUnit
    {
        AmperePerMetre,  // AmperePerMetre
        KiloamperePerMetre,  // KiloamperePerMetre
        Oersted,  // Oersted
    };
    // DEXPI 2.0 enumeration MagneticFluxDensityUnit (XMI id ID339)
    enum class MagneticFluxDensityUnit
    {
        Gauss,  // Gauss
        Tesla,  // Tesla
    };
    // DEXPI 2.0 enumeration MassConcentrationUnit (XMI id ID342)
    enum class MassConcentrationUnit
    {
        KilogramPerLitre,  // KilogramPerLitre
        KilogramPerMetreCubed,  // KilogramPerMetreCubed
        PoundMassPerFootCubed,  // PoundMassPerFootCubed
        PoundMassPerUsGallon,  // PoundMassPerUsGallon
    };
    // DEXPI 2.0 enumeration MassFlowRateUnit (XMI id ID347)
    enum class MassFlowRateUnit
    {
        KilogramPerHour,  // KilogramPerHour
        KilogramPerMinute,  // KilogramPerMinute
        KilogramPerSecond,  // KilogramPerSecond
        PoundMassPerHour,  // PoundMassPerHour
        PoundMassPerMinute,  // PoundMassPerMinute
        PoundMassPerSecond,  // PoundMassPerSecond
    };
    // DEXPI 2.0 enumeration MassSpecificEnergyUnit (XMI id ID354)
    enum class MassSpecificEnergyUnit
    {
        KilojoulePerKilogram,  // KilojoulePerKilogram
        MegajoulePerKilogram,  // MegajoulePerKilogram
    };
    // DEXPI 2.0 enumeration MassSpecificHeatCapacityUnit (XMI id ID357)
    enum class MassSpecificHeatCapacityUnit
    {
        BtuITPerPoundDegreeFahrenheit,  // BtuITPerPoundDegreeFahrenheit
        KilojoulePerKilogramKelvin,  // KilojoulePerKilogramKelvin
    };
    // DEXPI 2.0 enumeration MassUnit (XMI id ID360)
    enum class MassUnit
    {
        Gram,  // Gram
        Kilogram,  // Kilogram
        PoundMass,  // PoundMass
        Tonne,  // Tonne
    };
    // DEXPI 2.0 enumeration MoleConcentrationUnit (XMI id ID365)
    enum class MoleConcentrationUnit
    {
        MillimolePerLitre,  // MillimolePerLitre
        MolePerLitre,  // MolePerLitre
    };
    // DEXPI 2.0 enumeration MoleFlowRateUnit (XMI id ID368)
    enum class MoleFlowRateUnit
    {
        KilomolePerSecond,  // KilomolePerSecond
        PoundMolePerSecond,  // PoundMolePerSecond
    };
    // DEXPI 2.0 enumeration MoleSpecificEnergyUnit (XMI id ID371)
    enum class MoleSpecificEnergyUnit
    {
        JoulePerMole,  // JoulePerMole
        KilocaloriePerMole,  // KilocaloriePerMole
        KilojoulePerKilomole,  // KilojoulePerKilomole
        KilojoulePerMole,  // KilojoulePerMole
    };
    // DEXPI 2.0 enumeration MomentOfForceUnit (XMI id ID376)
    enum class MomentOfForceUnit
    {
        NewtonMetre,  // NewtonMetre
        PoundForceFoot,  // PoundForceFoot
    };
    // DEXPI 2.0 enumeration NumberPerTimeIntervalUnit (XMI id ID379)
    enum class NumberPerTimeIntervalUnit
    {
        ReciprocalMinute,  // ReciprocalMinute
        ReciprocalSecond,  // ReciprocalSecond
    };
    // DEXPI 2.0 enumeration ParticleSizeUnit (XMI id ID382)
    enum class ParticleSizeUnit
    {
        Inch,  // Inch
        Micrometre,  // Micrometre
        Millimetre,  // Millimetre
    };
    // DEXPI 2.0 enumeration PercentageUnit (XMI id ID386)
    enum class PercentageUnit
    {
        Percent,  // Percent
    };
    // DEXPI 2.0 enumeration PowerUnit (XMI id ID395)
    enum class PowerUnit
    {
        Kilowatt,  // Kilowatt
        Megawatt,  // Megawatt
        Watt,  // Watt
    };
    // DEXPI 2.0 enumeration PressureAbsoluteUnit (XMI id ID399)
    enum class PressureAbsoluteUnit
    {
        Bar,  // Bar
        Kilopascal,  // Kilopascal
        Megapascal,  // Megapascal
        Millibar,  // Millibar
        Pascal,  // Pascal
        PoundForcePerInchSquared,  // PoundForcePerInchSquared
    };
    // DEXPI 2.0 enumeration PressureGaugeUnit (XMI id ID407)
    enum class PressureGaugeUnit
    {
        Bar,  // Bar
        Kilopascal,  // Kilopascal
        Megapascal,  // Megapascal
        Millibar,  // Millibar
        Pascal,  // Pascal
        PoundForcePerInchSquared,  // PoundForcePerInchSquared
    };
    // DEXPI 2.0 enumeration RotationalFrequencyUnit (XMI id ID414)
    enum class RotationalFrequencyUnit
    {
        ReciprocalMinute,  // ReciprocalMinute
        ReciprocalSecond,  // ReciprocalSecond
    };
    // DEXPI 2.0 enumeration SurfaceTensionUnit (XMI id ID417)
    enum class SurfaceTensionUnit
    {
        DynePerCentimetre,  // DynePerCentimetre
        NewtonPerMetre,  // NewtonPerMetre
        PoundForcePerInch,  // PoundForcePerInch
    };
    // DEXPI 2.0 enumeration TemperatureUnit (XMI id ID421)
    enum class TemperatureUnit
    {
        DegreeCelsius,  // DegreeCelsius
        DegreeFahrenheit,  // DegreeFahrenheit
        Kelvin,  // Kelvin
    };
    // DEXPI 2.0 enumeration ThermalConductivityUnit (XMI id ID425)
    enum class ThermalConductivityUnit
    {
        BtuITPerHourFootDegreeFahrenheit,  // BtuITPerHourFootDegreeFahrenheit
        WattPerMetreKelvin,  // WattPerMetreKelvin
    };
    // DEXPI 2.0 enumeration TimeIntervalUnit (XMI id ID428)
    enum class TimeIntervalUnit
    {
        Day,  // Day
        Hour,  // Hour
        Millisecond,  // Millisecond
        Minute,  // Minute
        Month,  // Month
        Second,  // Second
        Year,  // Year
    };
    // DEXPI 2.0 enumeration VelocityUnit (XMI id ID436)
    enum class VelocityUnit
    {
        FootPerSecond,  // FootPerSecond
        KilometrePerHour,  // KilometrePerHour
        MetrePerSecond,  // MetrePerSecond
        MilePerHour,  // MilePerHour
        NauticalMilePerHour,  // NauticalMilePerHour
    };
    // DEXPI 2.0 enumeration VoltageUnit (XMI id ID442)
    enum class VoltageUnit
    {
        KiloVolt,  // KiloVolt
        MegaVolt,  // MegaVolt
        Volt,  // Volt
    };
    // DEXPI 2.0 enumeration VolumeFlowRateUnit (XMI id ID446)
    enum class VolumeFlowRateUnit
    {
        FootCubedPerHour,  // FootCubedPerHour
        FootCubedPerMinute,  // FootCubedPerMinute
        LitrePerSecond,  // LitrePerSecond
        MetreCubedPerDay,  // MetreCubedPerDay
        MetreCubedPerHour,  // MetreCubedPerHour
        MetreCubedPerMinute,  // MetreCubedPerMinute
        MetreCubedPerSecond,  // MetreCubedPerSecond
    };
    // DEXPI 2.0 enumeration VolumeUnit (XMI id ID454)
    enum class VolumeUnit
    {
        CentimetreCubed,  // CentimetreCubed
        DecimetreCubed,  // DecimetreCubed
        FootCubed,  // FootCubed
        Litre,  // Litre
        MetreCubed,  // MetreCubed
        UsFluidOunce,  // UsFluidOunce
        UsGallon,  // UsGallon
    };
    // DEXPI 2.0 enumeration pHUnit (XMI id ID462)
    enum class pHUnit
    {
        pH,  // pH
    };
} // namespace physicalquantities
} // namespace core

namespace core {
    // DEXPI 2.0 model class ConceptualObject (XMI id ID11) [abstract in DEXPI]
    class ConceptualObject
    {
    public:
        virtual ~ConceptualObject() = default;
        std::vector<std::shared_ptr<Role>> PerformedRoles;
        std::vector<std::shared_ptr<PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<Note>> ReferencedNotes;

    protected:
        ConceptualObject() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class EngineeringModel (XMI id ID250)
    class EngineeringModel
    {
    public:
        virtual ~EngineeringModel() = default;
        std::shared_ptr<ConceptualModel> ConceptualModel;
        std::shared_ptr<dexpi2::core::diagram::Diagram> Diagram;
        std::string ExportDateTime;
        std::string OriginatingSystemName;
        std::string OriginatingSystemVendorName;
        std::string OriginatingSystemVersion;
        std::vector<std::shared_ptr<dexpi2::core::diagram::ShapeCatalogue>> ShapeCatalogues;

        EngineeringModel() = default;
    };
    // DEXPI 2.0 model class PersistentIdentifier (XMI id ID28)
    class PersistentIdentifier
    {
    public:
        virtual ~PersistentIdentifier() = default;
        std::string Context;
        std::string Value;

        PersistentIdentifier() = default;
    };
    // DEXPI 2.0 model class Role (XMI id ID21)
    class Role
    {
    public:
        virtual ~Role() = default;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string Name;
        std::optional<std::string> Uri;

        Role() = default;
    };
    // DEXPI 2.0 model class ConceptualModel (XMI id ID10) [abstract in DEXPI] [flattened; bases inlined: ConceptualObject]
    class ConceptualModel
    {
    public:
        virtual ~ConceptualModel() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<Role>> PerformedRoles;
        std::vector<std::shared_ptr<PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<Note>> ReferencedNotes;
        std::shared_ptr<dexpi2::core::diagram::MetaData> MetaData;
        std::vector<std::shared_ptr<Note>> Notes;
        std::vector<std::shared_ptr<Role>> Roles;

    protected:
        ConceptualModel() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class Note (XMI id ID17) [flattened; bases inlined: ConceptualObject]
    class Note
    {
    public:
        virtual ~Note() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<Role>> PerformedRoles;
        std::vector<std::shared_ptr<PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<Note>> ReferencedNotes;
        std::optional<std::string> LocalNoteIdentifier;
        std::optional<std::string> NoteClassification;
        std::optional<std::string> NoteRegistrationNumber;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> NoteText;

        Note() = default;
    };
    // DEXPI 2.0 model class QualifiedValue (XMI id ID464) [flattened; bases inlined: ConceptualObject]
    class QualifiedValue
    {
    public:
        virtual ~QualifiedValue() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<Role>> PerformedRoles;
        std::vector<std::shared_ptr<PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<Note>> ReferencedNotes;
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

        QualifiedValue() = default;
    };
} // namespace core

namespace core {
namespace datatypes {
    // DEXPI 2.0 model class MultiLanguageString (XMI id ID35)
    class MultiLanguageString
    {
    public:
        virtual ~MultiLanguageString() = default;
        std::vector<std::shared_ptr<SingleLanguageString>> SingleLanguageStrings;

        MultiLanguageString() = default;
    };
    // DEXPI 2.0 model class SingleLanguageString (XMI id ID37)
    class SingleLanguageString
    {
    public:
        virtual ~SingleLanguageString() = default;
        std::string Language;
        std::string Value;

        SingleLanguageString() = default;
    };
} // namespace datatypes
} // namespace core

namespace core {
namespace diagram {
    // DEXPI 2.0 model class Color (XMI id ID79)
    class Color
    {
    public:
        virtual ~Color() = default;
        int B = 0;
        int G = 0;
        int R = 0;

        Color() = default;
    };
    // DEXPI 2.0 model class GraphicalElement (XMI id ID137) [abstract in DEXPI]
    class GraphicalElement
    {
    public:
        virtual ~GraphicalElement() = default;

    protected:
        GraphicalElement() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class GraphicsGroup (XMI id ID138) [abstract in DEXPI]
    class GraphicsGroup
    {
    public:
        virtual ~GraphicsGroup() = default;

    protected:
        GraphicsGroup() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class NodePosition (XMI id ID91) [abstract in DEXPI]
    class NodePosition
    {
    public:
        virtual ~NodePosition() = default;
        std::shared_ptr<Point> Position;

    protected:
        NodePosition() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class Point (XMI id ID89)
    class Point
    {
    public:
        virtual ~Point() = default;
        double X = 0.0;
        double Y = 0.0;

        Point() = default;
    };
    // DEXPI 2.0 model class Shape (XMI id ID201)
    class Shape
    {
    public:
        virtual ~Shape() = default;
        std::string Name;
        std::vector<std::shared_ptr<GraphicalPrimitive>> Primitives;
        std::string SymbolRegistrationNumber;

        Shape() = default;
    };
    // DEXPI 2.0 model class ShapeCatalogue (XMI id ID207)
    class ShapeCatalogue
    {
    public:
        virtual ~ShapeCatalogue() = default;
        std::string Name;
        std::vector<std::shared_ptr<Shape>> Shapes;

        ShapeCatalogue() = default;
    };
    // DEXPI 2.0 model class Stroke (XMI id ID95)
    class Stroke
    {
    public:
        virtual ~Stroke() = default;
        std::shared_ptr<Color> Color;
        DashStyle DashStyle{};
        double Width = 0.0;

        Stroke() = default;
    };
    // DEXPI 2.0 model class TextTemplate (XMI id ID234)
    class TextTemplate
    {
    public:
        virtual ~TextTemplate() = default;
        std::vector<std::shared_ptr<TextTemplateFragment>> Fragments;

        TextTemplate() = default;
    };
    // DEXPI 2.0 model class TextTemplateFragment (XMI id ID67) [abstract in DEXPI]
    class TextTemplateFragment
    {
    public:
        virtual ~TextTemplateFragment() = default;

    protected:
        TextTemplateFragment() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class MetaData (XMI id ID13) [flattened; bases inlined: ConceptualObject]
    class MetaData
    {
    public:
        virtual ~MetaData() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        std::optional<std::string> ApprovalDateRepresentation;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> ApprovalDescription;
        std::optional<std::string> ApproverName;
        std::optional<std::string> ArchiveNumber;
        std::optional<std::string> BlockName;
        std::optional<std::string> BlockNumber;
        std::optional<std::string> CheckerName;
        std::optional<ConfidentialityClassification> Confidentiality;
        std::optional<std::string> CreationDateRepresentation;
        std::optional<std::string> CreatorName;
        std::optional<std::string> DesignerName;
        std::optional<std::string> DrafterName;
        std::optional<std::string> DrawingName;
        std::optional<std::string> DrawingNumber;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> DrawingSubTitle;
        std::optional<std::string> FileName;
        std::optional<std::string> LastModificationDateRepresentation;
        std::optional<std::string> LocationName;
        std::optional<std::string> ProcessCellIdentificationCode;
        std::optional<std::string> ProcessCellName;
        std::optional<std::string> ProjectName;
        std::optional<std::string> ProjectNumber;
        std::optional<std::string> ProjectRangeNumber;
        std::optional<std::string> ReplacedDrawing;
        std::optional<std::string> ResponsibleDepartmentName;
        std::optional<std::string> RevisionNumber;
        std::optional<std::string> SheetFormat;
        std::optional<std::string> SheetNumber;
        std::optional<std::string> SubProjectName;
        std::optional<std::string> SubProjectNumber;
        std::optional<int> TotalNumberOfSheets;
        std::optional<std::string> UnitIdentificationCode;
        std::optional<std::string> UnitName;

        MetaData() = default;
    };
    // DEXPI 2.0 model class GraphicalPrimitive (XMI id ID87) [abstract in DEXPI] [flattened; bases inlined: GraphicalElement]
    class GraphicalPrimitive
    {
    public:
        virtual ~GraphicalPrimitive() = default;

    protected:
        GraphicalPrimitive() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class ShapeUsage (XMI id ID212) [flattened; bases inlined: GraphicalElement]
    class ShapeUsage
    {
    public:
        virtual ~ShapeUsage() = default;
        bool IsMirrored = false;
        std::shared_ptr<Point> Position;
        double Rotation = 0.0;
        double ScaleX = 0.0;
        double ScaleY = 0.0;
        std::shared_ptr<Shape> Shape;

        ShapeUsage() = default;
    };
    // DEXPI 2.0 model class RepresentationGroup (XMI id ID111) [flattened; bases inlined: GraphicsGroup]
    class RepresentationGroup
    {
    public:
        virtual ~RepresentationGroup() = default;
        std::vector<std::shared_ptr<GraphicsGroup>> Groups;
        std::vector<std::shared_ptr<NodePosition>> NodePositions;
        std::shared_ptr<dexpi2::core::ConceptualObject> Represents;

        RepresentationGroup() = default;
    };
    // DEXPI 2.0 model class RepresentationTypeGroup (XMI id ID78) [abstract in DEXPI] [flattened; bases inlined: GraphicsGroup]
    class RepresentationTypeGroup
    {
    public:
        virtual ~RepresentationTypeGroup() = default;
        std::vector<std::shared_ptr<GraphicalElement>> Elements;

    protected:
        RepresentationTypeGroup() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class AttributeRepresentation (XMI id ID66) [flattened; bases inlined: TextTemplateFragment]
    class AttributeRepresentation
    {
    public:
        virtual ~AttributeRepresentation() = default;
        std::string AttributeName;
        std::shared_ptr<dexpi2::core::ConceptualObject> Object;
        AttributeRepresentationType Type{};

        AttributeRepresentation() = default;
    };
    // DEXPI 2.0 model class LiteralText (XMI id ID141) [flattened; bases inlined: TextTemplateFragment]
    class LiteralText
    {
    public:
        virtual ~LiteralText() = default;
        std::string Text;

        LiteralText() = default;
    };
    // DEXPI 2.0 model class ConnectorLine (XMI id ID86) [flattened; bases inlined: GraphicalPrimitive]
    class ConnectorLine
    {
    public:
        virtual ~ConnectorLine() = default;
        std::vector<std::shared_ptr<Point>> InnerPoints;
        std::shared_ptr<NodePosition> Source;
        std::shared_ptr<Stroke> Stroke;
        std::shared_ptr<NodePosition> Target;

        ConnectorLine() = default;
    };
    // DEXPI 2.0 model class Ellipse (XMI id ID118) [flattened; bases inlined: GraphicalPrimitive]
    class Ellipse
    {
    public:
        virtual ~Ellipse() = default;
        std::shared_ptr<Point> Center;
        FillStyle FillStyle{};
        double HorizontalSemiAxis = 0.0;
        double Rotation = 0.0;
        std::shared_ptr<Stroke> Stroke;
        double VerticalSemiAxis = 0.0;

        Ellipse() = default;
    };
    // DEXPI 2.0 model class EllipseArc (XMI id ID126) [flattened; bases inlined: GraphicalPrimitive]
    class EllipseArc
    {
    public:
        virtual ~EllipseArc() = default;
        std::shared_ptr<Point> Center;
        double EndAngle = 0.0;
        double HorizontalSemiAxis = 0.0;
        double Rotation = 0.0;
        double StartAngle = 0.0;
        std::shared_ptr<Stroke> Stroke;
        double VerticalSemiAxis = 0.0;

        EllipseArc() = default;
    };
    // DEXPI 2.0 model class PolyLine (XMI id ID182) [flattened; bases inlined: GraphicalPrimitive]
    class PolyLine
    {
    public:
        virtual ~PolyLine() = default;
        std::vector<std::shared_ptr<Point>> Points;
        std::shared_ptr<Stroke> Stroke;

        PolyLine() = default;
    };
    // DEXPI 2.0 model class Polygon (XMI id ID185) [flattened; bases inlined: GraphicalPrimitive]
    class Polygon
    {
    public:
        virtual ~Polygon() = default;
        FillStyle FillStyle{};
        std::vector<std::shared_ptr<Point>> Points;
        std::shared_ptr<Stroke> Stroke;

        Polygon() = default;
    };
    // DEXPI 2.0 model class Text (XMI id ID225) [flattened; bases inlined: GraphicalPrimitive]
    class Text
    {
    public:
        virtual ~Text() = default;
        TextAlignment Alignment{};
        std::shared_ptr<Color> Color;
        std::string Font;
        std::shared_ptr<Point> Position;
        double Rotation = 0.0;
        double Size = 0.0;
        std::shared_ptr<TextTemplate> Template;
        std::string Text_;

        Text() = default;
    };
    // DEXPI 2.0 model class Diagram (XMI id ID110) [flattened; bases inlined: RepresentationGroup]
    class Diagram
    {
    public:
        virtual ~Diagram() = default;
        // inherited from RepresentationGroup (XMI id ID111)
        std::vector<std::shared_ptr<GraphicsGroup>> Groups;
        std::vector<std::shared_ptr<NodePosition>> NodePositions;
        std::shared_ptr<dexpi2::core::ConceptualObject> Represents;
        std::shared_ptr<Color> BackgroundColor;
        double MaxX = 0.0;
        double MaxY = 0.0;
        double MinX = 0.0;
        double MinY = 0.0;
        std::string Name;

        Diagram() = default;
    };
    // DEXPI 2.0 model class Border (XMI id ID77) [flattened; bases inlined: RepresentationTypeGroup]
    class Border
    {
    public:
        virtual ~Border() = default;
        // inherited from RepresentationTypeGroup (XMI id ID78)
        std::vector<std::shared_ptr<GraphicalElement>> Elements;

        Border() = default;
    };
    // DEXPI 2.0 model class Label (XMI id ID140) [flattened; bases inlined: RepresentationTypeGroup]
    class Label
    {
    public:
        virtual ~Label() = default;
        // inherited from RepresentationTypeGroup (XMI id ID78)
        std::vector<std::shared_ptr<GraphicalElement>> Elements;

        Label() = default;
    };
    // DEXPI 2.0 model class Static (XMI id ID221) [flattened; bases inlined: RepresentationTypeGroup]
    class Static
    {
    public:
        virtual ~Static() = default;
        // inherited from RepresentationTypeGroup (XMI id ID78)
        std::vector<std::shared_ptr<GraphicalElement>> Elements;

        Static() = default;
    };
    // DEXPI 2.0 model class Symbol (XMI id ID100) [flattened; bases inlined: RepresentationTypeGroup]
    class Symbol
    {
    public:
        virtual ~Symbol() = default;
        // inherited from RepresentationTypeGroup (XMI id ID78)
        std::vector<std::shared_ptr<GraphicalElement>> Elements;

        Symbol() = default;
    };
    // DEXPI 2.0 model class CustomSymbol (XMI id ID99) [flattened; bases inlined: Symbol]
    class CustomSymbol
    {
    public:
        virtual ~CustomSymbol() = default;
        // inherited from RepresentationTypeGroup (XMI id ID78)
        std::vector<std::shared_ptr<GraphicalElement>> Elements;

        CustomSymbol() = default;
    };
    // DEXPI 2.0 model class InsulationSymbol (XMI id ID139) [flattened; bases inlined: Symbol]
    class InsulationSymbol
    {
    public:
        virtual ~InsulationSymbol() = default;
        // inherited from RepresentationTypeGroup (XMI id ID78)
        std::vector<std::shared_ptr<GraphicalElement>> Elements;

        InsulationSymbol() = default;
    };
    // DEXPI 2.0 model class PipeFlowArrow (XMI id ID178) [flattened; bases inlined: Symbol]
    class PipeFlowArrow
    {
    public:
        virtual ~PipeFlowArrow() = default;
        // inherited from RepresentationTypeGroup (XMI id ID78)
        std::vector<std::shared_ptr<GraphicalElement>> Elements;

        PipeFlowArrow() = default;
    };
    // DEXPI 2.0 model class PipeSlopeSymbol (XMI id ID179) [flattened; bases inlined: Symbol]
    class PipeSlopeSymbol
    {
    public:
        virtual ~PipeSlopeSymbol() = default;
        // inherited from RepresentationTypeGroup (XMI id ID78)
        std::vector<std::shared_ptr<GraphicalElement>> Elements;

        PipeSlopeSymbol() = default;
    };
} // namespace diagram
} // namespace core

namespace core {
namespace physicalquantities {
    // DEXPI 2.0 model class PhysicalQuantity (XMI id ID388)
    class PhysicalQuantity
    {
    public:
        virtual ~PhysicalQuantity() = default;
        std::shared_ptr<PhysicalQuantityUnit> Unit;
        double Value = 0.0;

        PhysicalQuantity() = default;
    };
    // DEXPI 2.0 model class PhysicalQuantityUnit (XMI id ID273) [abstract in DEXPI]
    class PhysicalQuantityUnit
    {
    public:
        virtual ~PhysicalQuantityUnit() = default;

    protected:
        PhysicalQuantityUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class PhysicalQuantityVector (XMI id ID391)
    class PhysicalQuantityVector
    {
    public:
        virtual ~PhysicalQuantityVector() = default;
        std::shared_ptr<PhysicalQuantityUnit> Unit;
        std::vector<double> Values;

        PhysicalQuantityVector() = default;
    };
    // DEXPI 2.0 model class FrequencyUnit (XMI id ID295) [abstract in DEXPI] [flattened; bases inlined: PhysicalQuantityUnit]
    class FrequencyUnit
    {
    public:
        virtual ~FrequencyUnit() = default;

    protected:
        FrequencyUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class PressureUnit (XMI id ID400) [abstract in DEXPI] [flattened; bases inlined: PhysicalQuantityUnit]
    class PressureUnit
    {
    public:
        virtual ~PressureUnit() = default;

    protected:
        PressureUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
} // namespace physicalquantities
} // namespace core
} // namespace dexpi2
