// <auto-generated>
// DEXPI 2.0 UML model -> C++ - flattened conversion by Dexpi2CppFlatten (rule version 1.0).
// Source: dexpi2.hpp (SHA-256: e81ff83c9093ec5e8464c61cfaff00cbf74b303f7da45423de0d19e3204b9f67)
// Abstract/concrete base classes are FULLY INLINED into every derived class (flat hierarchy):
//   - no class inherits from anything; every class is self-contained
//   - abstract classes remain as reference types, still marked [abstract in DEXPI]
//   - C++ shadowing: a derived member with the same name as an inherited one wins
// Top-level namespace: dexpi2::auxiliaries
// </auto-generated>
#pragma once

#include <memory>
#include <optional>
#include <string>
#include <vector>

#include "dexpi2_core.hpp"

// Forward declarations for every model class in this file (std::shared_ptr members accept incomplete types).
namespace dexpi2 {
namespace auxiliaries {
    class QualifiedValueOfPhysicalQuantitywithUnitTypeForceUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeRotationalFrequencyUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypePowerUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypePercentageUnit;
    class QualifiedValueOfDouble;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeMassFlowRateUnit;
    class QualifiedValueOfPhysicalQuantityVectorwithUnitTypePercentageUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeMoleFlowRateUnit;
    class QualifiedValueOfInteger;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeLengthUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypePressureAbsoluteUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeTemperatureUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeAreaUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeElectricCurrentUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeElectricalFrequencyUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeVoltageUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeVolumeFlowRateUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeHeatTransferCoefficientUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeHeatTransferResistanceUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeMassUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeParticleSizeUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeDensityUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeMassSpecificEnergyUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeDynamicViscosityUnit;
    class QualifiedValueOfPhysicalQuantity;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeMomentOfForceUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeTimeIntervalUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeVolumeUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeVelocityUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeMagneticFieldIntensityUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypepHUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeEnergyUnit;
    class QualifiedValueOfPhysicalQuantitywithUnitTypeEnergyDensityUnit;
} // namespace auxiliaries
} // namespace dexpi2

namespace dexpi2 {

namespace auxiliaries {
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=ForceUnit)) (XMI id ID1966) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeForceUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeForceUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeForceUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=RotationalFrequencyUnit)) (XMI id ID1971) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeRotationalFrequencyUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeRotationalFrequencyUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeRotationalFrequencyUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=PowerUnit)) (XMI id ID1981) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypePowerUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypePowerUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypePowerUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=PercentageUnit)) (XMI id ID1990) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypePercentageUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypePercentageUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypePercentageUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | Double) (XMI id ID1998) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfDouble
    {
    public:
        virtual ~QualifiedValueOfDouble() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        double Value = 0.0;

    protected:
        QualifiedValueOfDouble() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=MassFlowRateUnit)) (XMI id ID2025) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeMassFlowRateUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeMassFlowRateUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeMassFlowRateUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantityVector with UnitType=PercentageUnit)) (XMI id ID2034) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantityVectorwithUnitTypePercentageUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantityVectorwithUnitTypePercentageUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantityVector> Value;

    protected:
        QualifiedValueOfPhysicalQuantityVectorwithUnitTypePercentageUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=MoleFlowRateUnit)) (XMI id ID2042) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeMoleFlowRateUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeMoleFlowRateUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeMoleFlowRateUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | Integer) (XMI id ID2056) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfInteger
    {
    public:
        virtual ~QualifiedValueOfInteger() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        int Value = 0;

    protected:
        QualifiedValueOfInteger() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=LengthUnit)) (XMI id ID2064) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeLengthUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeLengthUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeLengthUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=PressureAbsoluteUnit)) (XMI id ID2110) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypePressureAbsoluteUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypePressureAbsoluteUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypePressureAbsoluteUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=TemperatureUnit)) (XMI id ID2115) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeTemperatureUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeTemperatureUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeTemperatureUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=AreaUnit)) (XMI id ID2164) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeAreaUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeAreaUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeAreaUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=ElectricCurrentUnit)) (XMI id ID2180) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeElectricCurrentUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeElectricCurrentUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeElectricCurrentUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=ElectricalFrequencyUnit)) (XMI id ID2185) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeElectricalFrequencyUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeElectricalFrequencyUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeElectricalFrequencyUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=VoltageUnit)) (XMI id ID2193) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeVoltageUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeVoltageUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeVoltageUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=VolumeFlowRateUnit)) (XMI id ID2205) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeVolumeFlowRateUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeVolumeFlowRateUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeVolumeFlowRateUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=HeatTransferCoefficientUnit)) (XMI id ID2232) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeHeatTransferCoefficientUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeHeatTransferCoefficientUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeHeatTransferCoefficientUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=HeatTransferResistanceUnit)) (XMI id ID2240) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeHeatTransferResistanceUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeHeatTransferResistanceUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeHeatTransferResistanceUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=MassUnit)) (XMI id ID2258) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeMassUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeMassUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeMassUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=ParticleSizeUnit)) (XMI id ID2268) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeParticleSizeUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeParticleSizeUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeParticleSizeUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=DensityUnit)) (XMI id ID2432) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeDensityUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeDensityUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeDensityUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=MassSpecificEnergyUnit)) (XMI id ID2446) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeMassSpecificEnergyUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeMassSpecificEnergyUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeMassSpecificEnergyUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=DynamicViscosityUnit)) (XMI id ID2454) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeDynamicViscosityUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeDynamicViscosityUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeDynamicViscosityUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | PhysicalQuantity) (XMI id ID2482) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantity
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantity() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantity() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=MomentOfForceUnit)) (XMI id ID2503) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeMomentOfForceUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeMomentOfForceUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeMomentOfForceUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=TimeIntervalUnit)) (XMI id ID2529) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeTimeIntervalUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeTimeIntervalUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeTimeIntervalUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=VolumeUnit)) (XMI id ID2595) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeVolumeUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeVolumeUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeVolumeUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=VelocityUnit)) (XMI id ID2694) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeVelocityUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeVelocityUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeVelocityUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=MagneticFieldIntensityUnit)) (XMI id ID2712) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeMagneticFieldIntensityUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeMagneticFieldIntensityUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeMagneticFieldIntensityUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=pHUnit)) (XMI id ID2745) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypepHUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypepHUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypepHUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=EnergyUnit)) (XMI id ID2812) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeEnergyUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeEnergyUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeEnergyUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
    // DEXPI 2.0 model class QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=EnergyDensityUnit)) (XMI id ID2820) [abstract in DEXPI] [flattened; bases inlined: QualifiedValue]
    class QualifiedValueOfPhysicalQuantitywithUnitTypeEnergyDensityUnit
    {
    public:
        virtual ~QualifiedValueOfPhysicalQuantitywithUnitTypeEnergyDensityUnit() = default;
        // inherited from ConceptualObject (XMI id ID11)
        std::vector<std::shared_ptr<dexpi2::core::Role>> PerformedRoles;
        std::vector<std::shared_ptr<dexpi2::core::PersistentIdentifier>> PersistentIdentifiers;
        std::vector<std::shared_ptr<dexpi2::core::Note>> ReferencedNotes;
        // inherited from QualifiedValue (XMI id ID464)
        std::optional<std::string> Case;
        std::optional<std::string> CaseUID;
        std::shared_ptr<dexpi2::core::datatypes::MultiLanguageString> Description;
        std::string DisplayText;
        std::optional<dexpi2::core::datatypes::QuantityProvenance> Provenance;
        std::optional<std::string> ProvenanceURI;
        std::optional<dexpi2::core::datatypes::QuantityRange> Range;
        std::optional<std::string> ReferenceDataURI;
        std::optional<dexpi2::core::datatypes::Scope> Scope;
        std::optional<std::string> SourceURI;
        std::shared_ptr<dexpi2::core::physicalquantities::PhysicalQuantity> Value;

    protected:
        QualifiedValueOfPhysicalQuantitywithUnitTypeEnergyDensityUnit() = default;  // abstract in DEXPI: not directly instantiable
    };
} // namespace auxiliaries
} // namespace dexpi2
