// <auto-generated>
// DEXPI 2.0 UML model -> C# (flat, inheritance-free) conversion by Dexpi2CSharpGenerator.
// Source: dexpi2_core.hpp (flattened C++ headers, snapshot under Dexpi2.CSharp.Generator/input).
// Flat hierarchy: no class inherits from anything; every class is self-contained.
// Abstract DEXPI classes are emitted as C# 'abstract' classes (not directly instantiable).
// Regenerate with: dotnet run --project Dexpi2.CSharp.Generator
// </auto-generated>

using System;
using System.Collections.Generic;

namespace Dexpi2.Core.Datatypes
{
    /// <summary>DEXPI 2.0 enumeration QuantityProvenance (XMI id ID38)</summary>
    public enum QuantityProvenance
    {
        Calculated,
        Estimated,
        Observed,
        Set,
        Specified,
    }

    /// <summary>DEXPI 2.0 enumeration QuantityRange (XMI id ID44)</summary>
    public enum QuantityRange
    {
        Actual,
        Average,
        LowerLimit,
        Nominal,
        Normal,
        UpperLimit,
    }

    /// <summary>DEXPI 2.0 enumeration Scope (XMI id ID51)</summary>
    public enum Scope
    {
        Alarm,
        Allowable,
        Design,
        Expected,
        Incidental,
        Operating,
        Protection,
        Rated,
        Test,
        Warning,
    }

    /// <summary>DEXPI 2.0 model class MultiLanguageString (XMI id ID35)</summary>
    public class MultiLanguageString
    {
        // own members
        public List<SingleLanguageString> SingleLanguageStrings { get; set; } = new();
    }

    /// <summary>DEXPI 2.0 model class SingleLanguageString (XMI id ID37)</summary>
    public class SingleLanguageString
    {
        // own members
        public string Language { get; set; } = "";
        public string Value { get; set; } = "";
    }

}

namespace Dexpi2.Core.Diagram
{
    /// <summary>DEXPI 2.0 enumeration AttributeRepresentationType (XMI id ID73)</summary>
    public enum AttributeRepresentationType
    {
        Units,
        Value,
        ValueAndUnits,
    }

    /// <summary>DEXPI 2.0 enumeration ConfidentialityClassification (XMI id ID83)</summary>
    public enum ConfidentialityClassification
    {
        ConfidentialInformation,
        NonConfidentialInformation,
    }

    /// <summary>DEXPI 2.0 enumeration DashStyle (XMI id ID101)</summary>
    public enum DashStyle
    {
        Dash,
        DashShortDash,
        Dot,
        LongDash,
        LongDashShortDash,
        LongDashShortDashShortDash,
        ShortDash,
        Solid,
    }

    /// <summary>DEXPI 2.0 enumeration FillStyle (XMI id ID121)</summary>
    public enum FillStyle
    {
        Hatch,
        Solid,
        Transparent,
    }

    /// <summary>DEXPI 2.0 enumeration TextAlignment (XMI id ID227)</summary>
    public enum TextAlignment
    {
        CenterBottom,
        CenterCenter,
        CenterTop,
        LeftBottom,
        LeftCenter,
        LeftTop,
        RightBottom,
        RightCenter,
        RightTop,
    }

    /// <summary>DEXPI 2.0 model class Color (XMI id ID79)</summary>
    public class Color
    {
        // own members
        public int B { get; set; } = 0;
        public int G { get; set; } = 0;
        public int R { get; set; } = 0;
    }

    /// <summary>DEXPI 2.0 model class GraphicalElement (XMI id ID137) [abstract in DEXPI]</summary>
    public abstract class GraphicalElement
    {
        // own members (none)
    }

    /// <summary>DEXPI 2.0 model class GraphicsGroup (XMI id ID138) [abstract in DEXPI]</summary>
    public abstract class GraphicsGroup
    {
        // own members (none)
    }

    /// <summary>DEXPI 2.0 model class NodePosition (XMI id ID91) [abstract in DEXPI]</summary>
    public abstract class NodePosition
    {
        // own members
        public Point Position { get; set; } = null!;
    }

    /// <summary>DEXPI 2.0 model class Point (XMI id ID89)</summary>
    public class Point
    {
        // own members
        public double X { get; set; } = 0.0;
        public double Y { get; set; } = 0.0;
    }

    /// <summary>DEXPI 2.0 model class Shape (XMI id ID201)</summary>
    public class Shape
    {
        // own members
        public string Name { get; set; } = "";
        public List<GraphicalPrimitive> Primitives { get; set; } = new();
        public string SymbolRegistrationNumber { get; set; } = "";
    }

    /// <summary>DEXPI 2.0 model class ShapeCatalogue (XMI id ID207)</summary>
    public class ShapeCatalogue
    {
        // own members
        public string Name { get; set; } = "";
        public List<Shape> Shapes { get; set; } = new();
    }

    /// <summary>DEXPI 2.0 model class Stroke (XMI id ID95)</summary>
    public class Stroke
    {
        // own members
        public Color Color { get; set; } = null!;
    }

    /// <summary>DEXPI 2.0 model class TextTemplate (XMI id ID234)</summary>
    public class TextTemplate
    {
        // own members
        public List<TextTemplateFragment> Fragments { get; set; } = new();
    }

    /// <summary>DEXPI 2.0 model class TextTemplateFragment (XMI id ID67) [abstract in DEXPI]</summary>
    public abstract class TextTemplateFragment
    {
        // own members (none)
    }

    /// <summary>DEXPI 2.0 model class MetaData (XMI id ID13)</summary>
    public class MetaData
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // own members
        public string ApprovalDateRepresentation { get; set; } = "";
        public Dexpi2.Core.Datatypes.MultiLanguageString ApprovalDescription { get; set; } = null!;
        public string ApproverName { get; set; } = "";
        public string ArchiveNumber { get; set; } = "";
        public string BlockName { get; set; } = "";
        public string BlockNumber { get; set; } = "";
        public string CheckerName { get; set; } = "";
        public ConfidentialityClassification Confidentiality { get; set; } = default;
        public string CreationDateRepresentation { get; set; } = "";
        public string CreatorName { get; set; } = "";
        public string DesignerName { get; set; } = "";
        public string DrafterName { get; set; } = "";
        public string DrawingName { get; set; } = "";
        public string DrawingNumber { get; set; } = "";
        public Dexpi2.Core.Datatypes.MultiLanguageString DrawingSubTitle { get; set; } = null!;
        public string FileName { get; set; } = "";
        public string LastModificationDateRepresentation { get; set; } = "";
        public string LocationName { get; set; } = "";
        public string ProcessCellIdentificationCode { get; set; } = "";
        public string ProcessCellName { get; set; } = "";
        public string ProjectName { get; set; } = "";
        public string ProjectNumber { get; set; } = "";
        public string ProjectRangeNumber { get; set; } = "";
        public string ReplacedDrawing { get; set; } = "";
        public string ResponsibleDepartmentName { get; set; } = "";
        public string RevisionNumber { get; set; } = "";
        public string SheetFormat { get; set; } = "";
        public string SheetNumber { get; set; } = "";
        public string SubProjectName { get; set; } = "";
        public string SubProjectNumber { get; set; } = "";
        public int TotalNumberOfSheets { get; set; } = 0;
        public string UnitIdentificationCode { get; set; } = "";
        public string UnitName { get; set; } = "";
    }

    /// <summary>DEXPI 2.0 model class GraphicalPrimitive (XMI id ID87) [abstract in DEXPI]</summary>
    public abstract class GraphicalPrimitive
    {
        // inherited from GraphicalElement (XMI id ID137) (none)
        // own members (none)
    }

    /// <summary>DEXPI 2.0 model class ShapeUsage (XMI id ID212)</summary>
    public class ShapeUsage
    {
        // inherited from GraphicalElement (XMI id ID137) (none)
        // own members
        public bool IsMirrored { get; set; } = false;
        public Point Position { get; set; } = null!;
        public double Rotation { get; set; } = 0.0;
        public double ScaleX { get; set; } = 0.0;
        public double ScaleY { get; set; } = 0.0;
        public Shape Shape { get; set; } = null!;
    }

    /// <summary>DEXPI 2.0 model class RepresentationGroup (XMI id ID111)</summary>
    public class RepresentationGroup
    {
        // inherited from GraphicsGroup (XMI id ID138) (none)
        // own members
        public List<GraphicsGroup> Groups { get; set; } = new();
        public List<NodePosition> NodePositions { get; set; } = new();
        public Dexpi2.Core.ConceptualObject Represents { get; set; } = null!;
    }

    /// <summary>DEXPI 2.0 model class RepresentationTypeGroup (XMI id ID78) [abstract in DEXPI]</summary>
    public abstract class RepresentationTypeGroup
    {
        // inherited from GraphicsGroup (XMI id ID138) (none)
        // own members
        public List<GraphicalElement> Elements { get; set; } = new();
    }

    /// <summary>DEXPI 2.0 model class AttributeRepresentation (XMI id ID66)</summary>
    public class AttributeRepresentation
    {
        // inherited from TextTemplateFragment (XMI id ID67) (none)
        // own members
        public string AttributeName { get; set; } = "";
        public Dexpi2.Core.ConceptualObject Object { get; set; } = null!;
    }

    /// <summary>DEXPI 2.0 model class LiteralText (XMI id ID141)</summary>
    public class LiteralText
    {
        // inherited from TextTemplateFragment (XMI id ID67) (none)
        // own members
        public string Text { get; set; } = "";
    }

    /// <summary>DEXPI 2.0 model class ConnectorLine (XMI id ID86)</summary>
    public class ConnectorLine
    {
        // inherited from GraphicalElement (XMI id ID137) (none)
        // inherited from GraphicalPrimitive (XMI id ID87) (none)
        // own members
        public List<Point> InnerPoints { get; set; } = new();
        public NodePosition Source { get; set; } = null!;
        public Stroke Stroke { get; set; } = null!;
        public NodePosition Target { get; set; } = null!;
    }

    /// <summary>DEXPI 2.0 model class Ellipse (XMI id ID118)</summary>
    public class Ellipse
    {
        // inherited from GraphicalElement (XMI id ID137) (none)
        // inherited from GraphicalPrimitive (XMI id ID87) (none)
        // own members
        public Point Center { get; set; } = null!;
    }

    /// <summary>DEXPI 2.0 model class EllipseArc (XMI id ID126)</summary>
    public class EllipseArc
    {
        // inherited from GraphicalElement (XMI id ID137) (none)
        // inherited from GraphicalPrimitive (XMI id ID87) (none)
        // own members
        public Point Center { get; set; } = null!;
        public double EndAngle { get; set; } = 0.0;
        public double HorizontalSemiAxis { get; set; } = 0.0;
        public double Rotation { get; set; } = 0.0;
        public double StartAngle { get; set; } = 0.0;
        public Stroke Stroke { get; set; } = null!;
        public double VerticalSemiAxis { get; set; } = 0.0;
    }

    /// <summary>DEXPI 2.0 model class PolyLine (XMI id ID182)</summary>
    public class PolyLine
    {
        // inherited from GraphicalElement (XMI id ID137) (none)
        // inherited from GraphicalPrimitive (XMI id ID87) (none)
        // own members
        public List<Point> Points { get; set; } = new();
        public Stroke Stroke { get; set; } = null!;
    }

    /// <summary>DEXPI 2.0 model class Polygon (XMI id ID185)</summary>
    public class Polygon
    {
        // inherited from GraphicalElement (XMI id ID137) (none)
        // inherited from GraphicalPrimitive (XMI id ID87) (none)
        // own members (none)
    }

    /// <summary>DEXPI 2.0 model class Text (XMI id ID225)</summary>
    public class Text
    {
        // inherited from GraphicalElement (XMI id ID137) (none)
        // inherited from GraphicalPrimitive (XMI id ID87) (none)
        // own members (none)
    }

    /// <summary>DEXPI 2.0 model class Diagram (XMI id ID110)</summary>
    public class Diagram
    {
        // inherited from GraphicsGroup (XMI id ID138) (none)
        // inherited from RepresentationGroup (XMI id ID111)
        public List<GraphicsGroup> Groups { get; set; } = new();
        public List<NodePosition> NodePositions { get; set; } = new();
        public Dexpi2.Core.ConceptualObject Represents { get; set; } = null!;
        // own members
        public Color BackgroundColor { get; set; } = null!;
        public double MaxX { get; set; } = 0.0;
        public double MaxY { get; set; } = 0.0;
        public double MinX { get; set; } = 0.0;
        public double MinY { get; set; } = 0.0;
        public string Name { get; set; } = "";
    }

    /// <summary>DEXPI 2.0 model class Border (XMI id ID77)</summary>
    public class Border
    {
        // inherited from GraphicsGroup (XMI id ID138) (none)
        // inherited from RepresentationTypeGroup (XMI id ID78)
        public List<GraphicalElement> Elements { get; set; } = new();
        // own members (none)
    }

    /// <summary>DEXPI 2.0 model class Label (XMI id ID140)</summary>
    public class Label
    {
        // inherited from GraphicsGroup (XMI id ID138) (none)
        // inherited from RepresentationTypeGroup (XMI id ID78)
        public List<GraphicalElement> Elements { get; set; } = new();
        // own members (none)
    }

    /// <summary>DEXPI 2.0 model class Static (XMI id ID221)</summary>
    public class Static
    {
        // inherited from GraphicsGroup (XMI id ID138) (none)
        // inherited from RepresentationTypeGroup (XMI id ID78)
        public List<GraphicalElement> Elements { get; set; } = new();
        // own members (none)
    }

    /// <summary>DEXPI 2.0 model class Symbol (XMI id ID100)</summary>
    public class Symbol
    {
        // inherited from GraphicsGroup (XMI id ID138) (none)
        // inherited from RepresentationTypeGroup (XMI id ID78)
        public List<GraphicalElement> Elements { get; set; } = new();
        // own members (none)
    }

    /// <summary>DEXPI 2.0 model class CustomSymbol (XMI id ID99)</summary>
    public class CustomSymbol
    {
        // inherited from GraphicsGroup (XMI id ID138) (none)
        // inherited from RepresentationTypeGroup (XMI id ID78)
        public List<GraphicalElement> Elements { get; set; } = new();
        // inherited from Symbol (XMI id ID100) (none)
        // own members (none)
    }

    /// <summary>DEXPI 2.0 model class InsulationSymbol (XMI id ID139)</summary>
    public class InsulationSymbol
    {
        // inherited from GraphicsGroup (XMI id ID138) (none)
        // inherited from RepresentationTypeGroup (XMI id ID78)
        public List<GraphicalElement> Elements { get; set; } = new();
        // inherited from Symbol (XMI id ID100) (none)
        // own members (none)
    }

    /// <summary>DEXPI 2.0 model class PipeFlowArrow (XMI id ID178)</summary>
    public class PipeFlowArrow
    {
        // inherited from GraphicsGroup (XMI id ID138) (none)
        // inherited from RepresentationTypeGroup (XMI id ID78)
        public List<GraphicalElement> Elements { get; set; } = new();
        // inherited from Symbol (XMI id ID100) (none)
        // own members (none)
    }

    /// <summary>DEXPI 2.0 model class PipeSlopeSymbol (XMI id ID179)</summary>
    public class PipeSlopeSymbol
    {
        // inherited from GraphicsGroup (XMI id ID138) (none)
        // inherited from RepresentationTypeGroup (XMI id ID78)
        public List<GraphicalElement> Elements { get; set; } = new();
        // inherited from Symbol (XMI id ID100) (none)
        // own members (none)
    }

}

namespace Dexpi2.Core.Physicalquantities
{
    /// <summary>DEXPI 2.0 enumeration AreaUnit (XMI id ID272)</summary>
    public enum AreaUnit
    {
        CentimetreSquared,
        FootSquared,
        InchSquared,
        MetreSquared,
        MillimetreSquared,
        YardSquared,
    }

    /// <summary>DEXPI 2.0 enumeration DensityUnit (XMI id ID280)</summary>
    public enum DensityUnit
    {
        KilogramPerLitre,
        KilogramPerMetreCubed,
        PoundMassPerFootCubed,
        PoundMassPerUsGallon,
    }

    /// <summary>DEXPI 2.0 enumeration DynamicViscosityUnit (XMI id ID285)</summary>
    public enum DynamicViscosityUnit
    {
        Centipoise,
        MillipascalSecond,
        PascalSecond,
        Poise,
    }

    /// <summary>DEXPI 2.0 enumeration ElectricCurrentUnit (XMI id ID290)</summary>
    public enum ElectricCurrentUnit
    {
        Ampere,
        Kiloampere,
        Milliampere,
    }

    /// <summary>DEXPI 2.0 enumeration ElectricalFrequencyUnit (XMI id ID294)</summary>
    public enum ElectricalFrequencyUnit
    {
        Hertz,
        KiloHertz,
        MegaHertz,
    }

    /// <summary>DEXPI 2.0 enumeration EnergyDensityUnit (XMI id ID299)</summary>
    public enum EnergyDensityUnit
    {
        JoulePerCubicMetre,
        KilojoulePerCubicMetre,
    }

    /// <summary>DEXPI 2.0 enumeration EnergyUnit (XMI id ID302)</summary>
    public enum EnergyUnit
    {
        Joule,
        Kilojoule,
        KilowattHour,
        Megajoule,
        MegawattHour,
    }

    /// <summary>DEXPI 2.0 enumeration ForceUnit (XMI id ID308)</summary>
    public enum ForceUnit
    {
        KiloNewton,
        Newton,
    }

    /// <summary>DEXPI 2.0 enumeration HeatCapacityUnit (XMI id ID311)</summary>
    public enum HeatCapacityUnit
    {
        BtuITPerDegreeFahrenheit,
        BtuThPerDegreeFahrenheit,
        WattPerKelvin,
    }

    /// <summary>DEXPI 2.0 enumeration HeatTransferCoefficientUnit (XMI id ID315)</summary>
    public enum HeatTransferCoefficientUnit
    {
        KilowattPerMetreSquaredKelvin,
        WattPerMetreSquaredKelvin,
    }

    /// <summary>DEXPI 2.0 enumeration HeatTransferResistanceUnit (XMI id ID318)</summary>
    public enum HeatTransferResistanceUnit
    {
        FootSquaredHourDegreeFahrenheitPerBtuTh,
        MetreSquaredKelvinPerWatt,
    }

    /// <summary>DEXPI 2.0 enumeration KinematicViscosityUnit (XMI id ID321)</summary>
    public enum KinematicViscosityUnit
    {
        CentimetreSquaredPerSecond,
        Centistoke,
        MetreSquaredPerSecond,
        Stoke,
    }

    /// <summary>DEXPI 2.0 enumeration LengthUnit (XMI id ID326)</summary>
    public enum LengthUnit
    {
        Centimetre,
        Foot,
        Inch,
        Kilometre,
        Metre,
        Micrometre,
        Millimetre,
        Nanometre,
    }

    /// <summary>DEXPI 2.0 enumeration MagneticFieldIntensityUnit (XMI id ID335)</summary>
    public enum MagneticFieldIntensityUnit
    {
        AmperePerMetre,
        KiloamperePerMetre,
        Oersted,
    }

    /// <summary>DEXPI 2.0 enumeration MagneticFluxDensityUnit (XMI id ID339)</summary>
    public enum MagneticFluxDensityUnit
    {
        Gauss,
        Tesla,
    }

    /// <summary>DEXPI 2.0 enumeration MassConcentrationUnit (XMI id ID342)</summary>
    public enum MassConcentrationUnit
    {
        KilogramPerLitre,
        KilogramPerMetreCubed,
        PoundMassPerFootCubed,
        PoundMassPerUsGallon,
    }

    /// <summary>DEXPI 2.0 enumeration MassFlowRateUnit (XMI id ID347)</summary>
    public enum MassFlowRateUnit
    {
        KilogramPerHour,
        KilogramPerMinute,
        KilogramPerSecond,
        PoundMassPerHour,
        PoundMassPerMinute,
        PoundMassPerSecond,
    }

    /// <summary>DEXPI 2.0 enumeration MassSpecificEnergyUnit (XMI id ID354)</summary>
    public enum MassSpecificEnergyUnit
    {
        KilojoulePerKilogram,
        MegajoulePerKilogram,
    }

    /// <summary>DEXPI 2.0 enumeration MassSpecificHeatCapacityUnit (XMI id ID357)</summary>
    public enum MassSpecificHeatCapacityUnit
    {
        BtuITPerPoundDegreeFahrenheit,
        KilojoulePerKilogramKelvin,
    }

    /// <summary>DEXPI 2.0 enumeration MassUnit (XMI id ID360)</summary>
    public enum MassUnit
    {
        Gram,
        Kilogram,
        PoundMass,
        Tonne,
    }

    /// <summary>DEXPI 2.0 enumeration MoleConcentrationUnit (XMI id ID365)</summary>
    public enum MoleConcentrationUnit
    {
        MillimolePerLitre,
        MolePerLitre,
    }

    /// <summary>DEXPI 2.0 enumeration MoleFlowRateUnit (XMI id ID368)</summary>
    public enum MoleFlowRateUnit
    {
        KilomolePerSecond,
        PoundMolePerSecond,
    }

    /// <summary>DEXPI 2.0 enumeration MoleSpecificEnergyUnit (XMI id ID371)</summary>
    public enum MoleSpecificEnergyUnit
    {
        JoulePerMole,
        KilocaloriePerMole,
        KilojoulePerKilomole,
        KilojoulePerMole,
    }

    /// <summary>DEXPI 2.0 enumeration MomentOfForceUnit (XMI id ID376)</summary>
    public enum MomentOfForceUnit
    {
        NewtonMetre,
        PoundForceFoot,
    }

    /// <summary>DEXPI 2.0 enumeration NumberPerTimeIntervalUnit (XMI id ID379)</summary>
    public enum NumberPerTimeIntervalUnit
    {
        ReciprocalMinute,
        ReciprocalSecond,
    }

    /// <summary>DEXPI 2.0 enumeration ParticleSizeUnit (XMI id ID382)</summary>
    public enum ParticleSizeUnit
    {
        Inch,
        Micrometre,
        Millimetre,
    }

    /// <summary>DEXPI 2.0 enumeration PercentageUnit (XMI id ID386)</summary>
    public enum PercentageUnit
    {
        Percent,
    }

    /// <summary>DEXPI 2.0 enumeration PowerUnit (XMI id ID395)</summary>
    public enum PowerUnit
    {
        Kilowatt,
        Megawatt,
        Watt,
    }

    /// <summary>DEXPI 2.0 enumeration PressureAbsoluteUnit (XMI id ID399)</summary>
    public enum PressureAbsoluteUnit
    {
        Bar,
        Kilopascal,
        Megapascal,
        Millibar,
        Pascal,
        PoundForcePerInchSquared,
    }

    /// <summary>DEXPI 2.0 enumeration PressureGaugeUnit (XMI id ID407)</summary>
    public enum PressureGaugeUnit
    {
        Bar,
        Kilopascal,
        Megapascal,
        Millibar,
        Pascal,
        PoundForcePerInchSquared,
    }

    /// <summary>DEXPI 2.0 enumeration RotationalFrequencyUnit (XMI id ID414)</summary>
    public enum RotationalFrequencyUnit
    {
        ReciprocalMinute,
        ReciprocalSecond,
    }

    /// <summary>DEXPI 2.0 enumeration SurfaceTensionUnit (XMI id ID417)</summary>
    public enum SurfaceTensionUnit
    {
        DynePerCentimetre,
        NewtonPerMetre,
        PoundForcePerInch,
    }

    /// <summary>DEXPI 2.0 enumeration TemperatureUnit (XMI id ID421)</summary>
    public enum TemperatureUnit
    {
        DegreeCelsius,
        DegreeFahrenheit,
        Kelvin,
    }

    /// <summary>DEXPI 2.0 enumeration ThermalConductivityUnit (XMI id ID425)</summary>
    public enum ThermalConductivityUnit
    {
        BtuITPerHourFootDegreeFahrenheit,
        WattPerMetreKelvin,
    }

    /// <summary>DEXPI 2.0 enumeration TimeIntervalUnit (XMI id ID428)</summary>
    public enum TimeIntervalUnit
    {
        Day,
        Hour,
        Millisecond,
        Minute,
        Month,
        Second,
        Year,
    }

    /// <summary>DEXPI 2.0 enumeration VelocityUnit (XMI id ID436)</summary>
    public enum VelocityUnit
    {
        FootPerSecond,
        KilometrePerHour,
        MetrePerSecond,
        MilePerHour,
        NauticalMilePerHour,
    }

    /// <summary>DEXPI 2.0 enumeration VoltageUnit (XMI id ID442)</summary>
    public enum VoltageUnit
    {
        KiloVolt,
        MegaVolt,
        Volt,
    }

    /// <summary>DEXPI 2.0 enumeration VolumeFlowRateUnit (XMI id ID446)</summary>
    public enum VolumeFlowRateUnit
    {
        FootCubedPerHour,
        FootCubedPerMinute,
        LitrePerSecond,
        MetreCubedPerDay,
        MetreCubedPerHour,
        MetreCubedPerMinute,
        MetreCubedPerSecond,
    }

    /// <summary>DEXPI 2.0 enumeration VolumeUnit (XMI id ID454)</summary>
    public enum VolumeUnit
    {
        CentimetreCubed,
        DecimetreCubed,
        FootCubed,
        Litre,
        MetreCubed,
        UsFluidOunce,
        UsGallon,
    }

    /// <summary>DEXPI 2.0 enumeration pHUnit (XMI id ID462)</summary>
    public enum pHUnit
    {
        pH,
    }

    /// <summary>DEXPI 2.0 model class PhysicalQuantity (XMI id ID388)</summary>
    public class PhysicalQuantity
    {
        // own members
        public PhysicalQuantityUnit Unit { get; set; } = null!;
        public double Value { get; set; } = 0.0;
    }

    /// <summary>DEXPI 2.0 model class PhysicalQuantityUnit (XMI id ID273) [abstract in DEXPI]</summary>
    public abstract class PhysicalQuantityUnit
    {
        // own members (none)
    }

    /// <summary>DEXPI 2.0 model class PhysicalQuantityVector (XMI id ID391)</summary>
    public class PhysicalQuantityVector
    {
        // own members
        public PhysicalQuantityUnit Unit { get; set; } = null!;
        public List<double> Values { get; set; } = new();
    }

    /// <summary>DEXPI 2.0 model class FrequencyUnit (XMI id ID295) [abstract in DEXPI]</summary>
    public abstract class FrequencyUnit
    {
        // inherited from PhysicalQuantityUnit (XMI id ID273) (none)
        // own members (none)
    }

    /// <summary>DEXPI 2.0 model class PressureUnit (XMI id ID400) [abstract in DEXPI]</summary>
    public abstract class PressureUnit
    {
        // inherited from PhysicalQuantityUnit (XMI id ID273) (none)
        // own members (none)
    }

}

namespace Dexpi2.Core
{
    /// <summary>DEXPI 2.0 model class ConceptualObject (XMI id ID11) [abstract in DEXPI]</summary>
    public abstract class ConceptualObject
    {
        // own members
        public List<Role> PerformedRoles { get; set; } = new();
        public List<PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Note> ReferencedNotes { get; set; } = new();
    }

    /// <summary>DEXPI 2.0 model class EngineeringModel (XMI id ID250)</summary>
    public class EngineeringModel
    {
        // own members
        public ConceptualModel ConceptualModel { get; set; } = null!;
        public Dexpi2.Core.Diagram.Diagram Diagram { get; set; } = null!;
        public string ExportDateTime { get; set; } = "";
        public string OriginatingSystemName { get; set; } = "";
        public string OriginatingSystemVendorName { get; set; } = "";
        public string OriginatingSystemVersion { get; set; } = "";
        public List<Dexpi2.Core.Diagram.ShapeCatalogue> ShapeCatalogues { get; set; } = new();
    }

    /// <summary>DEXPI 2.0 model class PersistentIdentifier (XMI id ID28)</summary>
    public class PersistentIdentifier
    {
        // own members
        public string Context { get; set; } = "";
        public string Value { get; set; } = "";
    }

    /// <summary>DEXPI 2.0 model class Role (XMI id ID21)</summary>
    public class Role
    {
        // own members
        public Dexpi2.Core.Datatypes.MultiLanguageString Description { get; set; } = null!;
        public string Name { get; set; } = "";
        public string Uri { get; set; } = "";
    }

    /// <summary>DEXPI 2.0 model class ConceptualModel (XMI id ID10) [abstract in DEXPI]</summary>
    public abstract class ConceptualModel
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Role> PerformedRoles { get; set; } = new();
        public List<PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Note> ReferencedNotes { get; set; } = new();
        // own members
        public Dexpi2.Core.Diagram.MetaData MetaData { get; set; } = null!;
        public List<Note> Notes { get; set; } = new();
        public List<Role> Roles { get; set; } = new();
    }

    /// <summary>DEXPI 2.0 model class Note (XMI id ID17)</summary>
    public class Note
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Role> PerformedRoles { get; set; } = new();
        public List<PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Note> ReferencedNotes { get; set; } = new();
        // own members
        public string LocalNoteIdentifier { get; set; } = "";
        public string NoteClassification { get; set; } = "";
        public string NoteRegistrationNumber { get; set; } = "";
        public Dexpi2.Core.Datatypes.MultiLanguageString NoteText { get; set; } = null!;
    }

    /// <summary>DEXPI 2.0 model class QualifiedValue (XMI id ID464)</summary>
    public class QualifiedValue
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Role> PerformedRoles { get; set; } = new();
        public List<PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Note> ReferencedNotes { get; set; } = new();
        // own members
        public string Case { get; set; } = "";
        public string CaseUID { get; set; } = "";
        public Dexpi2.Core.Datatypes.MultiLanguageString Description { get; set; } = null!;
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance Provenance { get; set; } = default;
        public string ProvenanceURI { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityRange Range { get; set; } = default;
        public string ReferenceDataURI { get; set; } = "";
        public Dexpi2.Core.Datatypes.Scope Scope { get; set; } = default;
        public string SourceURI { get; set; } = "";
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity Value { get; set; } = null!;
    }

}

