// <auto-generated>
// DEXPI 2.0 UML model -> C# (flat, inheritance-free) conversion by Dexpi2CSharpGenerator.
// Source: dexpi2_auxiliaries.hpp (flattened C++ headers, snapshot under Dexpi2.CSharp.Generator/input).
// Flat hierarchy: no class inherits from anything; every class is self-contained.
// Abstract DEXPI classes are emitted as C# 'abstract' classes (not directly instantiable).
// Regenerate with: dotnet run --project Dexpi2.CSharp.Generator
// </auto-generated>

using System;
using System.Collections.Generic;

#nullable enable

namespace Dexpi2.Auxiliaries
{
    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeForceUnit (XMI id ID1966) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=ForceUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeForceUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeRotationalFrequencyUnit (XMI id ID1971) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=RotationalFrequencyUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeRotationalFrequencyUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypePowerUnit (XMI id ID1981) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=PowerUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypePowerUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypePercentageUnit (XMI id ID1990) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=PercentageUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypePercentageUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfDouble (XMI id ID1998) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | Double)</summary>
    public abstract class QualifiedValueOfDouble
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public double Value { get; set; } = 0.0;
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeMassFlowRateUnit (XMI id ID2025) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=MassFlowRateUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeMassFlowRateUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantityVectorwithUnitTypePercentageUnit (XMI id ID2034) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantityVector with UnitType=PercentageUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantityVectorwithUnitTypePercentageUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantityVector? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeMoleFlowRateUnit (XMI id ID2042) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=MoleFlowRateUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeMoleFlowRateUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfInteger (XMI id ID2056) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | Integer)</summary>
    public abstract class QualifiedValueOfInteger
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public int Value { get; set; } = 0;
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeLengthUnit (XMI id ID2064) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=LengthUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeLengthUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypePressureAbsoluteUnit (XMI id ID2110) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=PressureAbsoluteUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypePressureAbsoluteUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeTemperatureUnit (XMI id ID2115) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=TemperatureUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeTemperatureUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeAreaUnit (XMI id ID2164) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=AreaUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeAreaUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeElectricCurrentUnit (XMI id ID2180) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=ElectricCurrentUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeElectricCurrentUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeElectricalFrequencyUnit (XMI id ID2185) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=ElectricalFrequencyUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeElectricalFrequencyUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeVoltageUnit (XMI id ID2193) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=VoltageUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeVoltageUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeVolumeFlowRateUnit (XMI id ID2205) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=VolumeFlowRateUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeVolumeFlowRateUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeHeatTransferCoefficientUnit (XMI id ID2232) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=HeatTransferCoefficientUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeHeatTransferCoefficientUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeHeatTransferResistanceUnit (XMI id ID2240) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=HeatTransferResistanceUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeHeatTransferResistanceUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeMassUnit (XMI id ID2258) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=MassUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeMassUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeParticleSizeUnit (XMI id ID2268) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=ParticleSizeUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeParticleSizeUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeDensityUnit (XMI id ID2432) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=DensityUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeDensityUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeMassSpecificEnergyUnit (XMI id ID2446) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=MassSpecificEnergyUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeMassSpecificEnergyUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeDynamicViscosityUnit (XMI id ID2454) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=DynamicViscosityUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeDynamicViscosityUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantity (XMI id ID2482) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | PhysicalQuantity)</summary>
    public abstract class QualifiedValueOfPhysicalQuantity
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeMomentOfForceUnit (XMI id ID2503) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=MomentOfForceUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeMomentOfForceUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeTimeIntervalUnit (XMI id ID2529) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=TimeIntervalUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeTimeIntervalUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeVolumeUnit (XMI id ID2595) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=VolumeUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeVolumeUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeVelocityUnit (XMI id ID2694) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=VelocityUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeVelocityUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeMagneticFieldIntensityUnit (XMI id ID2712) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=MagneticFieldIntensityUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeMagneticFieldIntensityUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypepHUnit (XMI id ID2745) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=pHUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypepHUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeEnergyUnit (XMI id ID2812) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=EnergyUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeEnergyUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

    /// <summary>DEXPI 2.0 model class QualifiedValueOfPhysicalQuantitywithUnitTypeEnergyDensityUnit (XMI id ID2820) [abstract in DEXPI]; source comment: QualifiedValue with Type=(Undefined | (PhysicalQuantity with UnitType=EnergyDensityUnit))</summary>
    public abstract class QualifiedValueOfPhysicalQuantitywithUnitTypeEnergyDensityUnit
    {
        // inherited from ConceptualObject (XMI id ID11)
        public List<Dexpi2.Core.Role> PerformedRoles { get; set; } = new();
        public List<Dexpi2.Core.PersistentIdentifier> PersistentIdentifiers { get; set; } = new();
        public List<Dexpi2.Core.Note> ReferencedNotes { get; set; } = new();
        // inherited from QualifiedValue (XMI id ID464)
        public string? Case { get; set; }
        public string? CaseUID { get; set; }
        public Dexpi2.Core.Datatypes.MultiLanguageString? Description { get; set; }
        public string DisplayText { get; set; } = "";
        public Dexpi2.Core.Datatypes.QuantityProvenance? Provenance { get; set; }
        public string? ProvenanceURI { get; set; }
        public Dexpi2.Core.Datatypes.QuantityRange? Range { get; set; }
        public string? ReferenceDataURI { get; set; }
        public Dexpi2.Core.Datatypes.Scope? Scope { get; set; }
        public string? SourceURI { get; set; }
        public Dexpi2.Core.Physicalquantities.PhysicalQuantity? Value { get; set; }
    }

}

