// <auto-generated>
// 可区分联合：Dexpi2.Plant.Processequipment.TaggedPlantItem 的所有非抽象派生类型（含非叶类）。
// 每个案例荷载对应的 C# 类型（该类型的一个实例），类型来自 Dexpi2.CSharp 程序集。
// 生成方式：dotnet fsi FSharp.DEXPI2/tools/generate-tagged-plant-item-union.fsx
// 数据来源：Dexpi2.CSharp.Generator/input/*.hpp 中 "[flattened; bases inlined: ...]" 直系基类注释。
// </auto-generated>

namespace FSharp.DEXPI2.Plant.ProcessEquipment

open System
open Dexpi2.Plant.Processequipment

/// <summary>可区分联合：TaggedPlantItem 的所有非抽象派生类型（含非叶类）。每个案例荷载对应的 C# 类型。</summary>
type TaggedPlantItem =
    | Agglomerator of Dexpi2.Plant.Processequipment.Agglomerator
    | Agitator of Dexpi2.Plant.Processequipment.Agitator
    | AirCoolingSystem of Dexpi2.Plant.Processequipment.AirCoolingSystem
    | AirEjector of Dexpi2.Plant.Processequipment.AirEjector
    | AlternatingCurrentGenerator of Dexpi2.Plant.Processequipment.AlternatingCurrentGenerator
    | AlternatingCurrentMotor of Dexpi2.Plant.Processequipment.AlternatingCurrentMotor
    | AxialBlower of Dexpi2.Plant.Processequipment.AxialBlower
    | AxialCompressor of Dexpi2.Plant.Processequipment.AxialCompressor
    | AxialFan of Dexpi2.Plant.Processequipment.AxialFan
    | BatchWeigher of Dexpi2.Plant.Processequipment.BatchWeigher
    | Blower of Dexpi2.Plant.Processequipment.Blower
    | Boiler of Dexpi2.Plant.Processequipment.Boiler
    | Burner of Dexpi2.Plant.Processequipment.Burner
    | CentrifugalBlower of Dexpi2.Plant.Processequipment.CentrifugalBlower
    | CentrifugalCompressor of Dexpi2.Plant.Processequipment.CentrifugalCompressor
    | CentrifugalPump of Dexpi2.Plant.Processequipment.CentrifugalPump
    | Centrifuge of Dexpi2.Plant.Processequipment.Centrifuge
    | Chimney of Dexpi2.Plant.Processequipment.Chimney
    | CombustionEngine of Dexpi2.Plant.Processequipment.CombustionEngine
    | Compressor of Dexpi2.Plant.Processequipment.Compressor
    | ContinuousWeigher of Dexpi2.Plant.Processequipment.ContinuousWeigher
    | ConvectionDryer of Dexpi2.Plant.Processequipment.ConvectionDryer
    | Conveyor of Dexpi2.Plant.Processequipment.Conveyor
    | CoolingTower of Dexpi2.Plant.Processequipment.CoolingTower
    | Crusher of Dexpi2.Plant.Processequipment.Crusher
    | DirectCurrentGenerator of Dexpi2.Plant.Processequipment.DirectCurrentGenerator
    | DirectCurrentMotor of Dexpi2.Plant.Processequipment.DirectCurrentMotor
    | DryCoolingTower of Dexpi2.Plant.Processequipment.DryCoolingTower
    | Dryer of Dexpi2.Plant.Processequipment.Dryer
    | EjectorPump of Dexpi2.Plant.Processequipment.EjectorPump
    | ElectricGenerator of Dexpi2.Plant.Processequipment.ElectricGenerator
    | ElectricHeater of Dexpi2.Plant.Processequipment.ElectricHeater
    | ElectricalSeparator of Dexpi2.Plant.Processequipment.ElectricalSeparator
    | Extruder of Dexpi2.Plant.Processequipment.Extruder
    | Fan of Dexpi2.Plant.Processequipment.Fan
    | Feeder of Dexpi2.Plant.Processequipment.Feeder
    | Filter of Dexpi2.Plant.Processequipment.Filter
    | FilteringCentrifuge of Dexpi2.Plant.Processequipment.FilteringCentrifuge
    | Flare of Dexpi2.Plant.Processequipment.Flare
    | ForkliftTruck of Dexpi2.Plant.Processequipment.ForkliftTruck
    | Furnace of Dexpi2.Plant.Processequipment.Furnace
    | GasFilter of Dexpi2.Plant.Processequipment.GasFilter
    | GasTurbine of Dexpi2.Plant.Processequipment.GasTurbine
    | GravitationalSeparator of Dexpi2.Plant.Processequipment.GravitationalSeparator
    | Grinder of Dexpi2.Plant.Processequipment.Grinder
    | HeatExchanger of Dexpi2.Plant.Processequipment.HeatExchanger
    | HeatedSurfaceDryer of Dexpi2.Plant.Processequipment.HeatedSurfaceDryer
    | Heater of Dexpi2.Plant.Processequipment.Heater
    | Kneader of Dexpi2.Plant.Processequipment.Kneader
    | Lift of Dexpi2.Plant.Processequipment.Lift
    | LiquidFilter of Dexpi2.Plant.Processequipment.LiquidFilter
    | LoadingUnloadingSystem of Dexpi2.Plant.Processequipment.LoadingUnloadingSystem
    | MechanicalSeparator of Dexpi2.Plant.Processequipment.MechanicalSeparator
    | Mill of Dexpi2.Plant.Processequipment.Mill
    | Mixer of Dexpi2.Plant.Processequipment.Mixer
    | MobileTransportSystem of Dexpi2.Plant.Processequipment.MobileTransportSystem
    | Motor of Dexpi2.Plant.Processequipment.Motor
    | PackagingSystem of Dexpi2.Plant.Processequipment.PackagingSystem
    | PlateHeatExchanger of Dexpi2.Plant.Processequipment.PlateHeatExchanger
    | PressureVessel of Dexpi2.Plant.Processequipment.PressureVessel
    | ProcessColumn of Dexpi2.Plant.Processequipment.ProcessColumn
    | Pump of Dexpi2.Plant.Processequipment.Pump
    | RadialFan of Dexpi2.Plant.Processequipment.RadialFan
    | RailWaggon of Dexpi2.Plant.Processequipment.RailWaggon
    | ReciprocatingCompressor of Dexpi2.Plant.Processequipment.ReciprocatingCompressor
    | ReciprocatingExtruder of Dexpi2.Plant.Processequipment.ReciprocatingExtruder
    | ReciprocatingPressureAgglomerator of Dexpi2.Plant.Processequipment.ReciprocatingPressureAgglomerator
    | ReciprocatingPump of Dexpi2.Plant.Processequipment.ReciprocatingPump
    | RevolvingSieve of Dexpi2.Plant.Processequipment.RevolvingSieve
    | RotaryCompressor of Dexpi2.Plant.Processequipment.RotaryCompressor
    | RotaryMixer of Dexpi2.Plant.Processequipment.RotaryMixer
    | RotaryPump of Dexpi2.Plant.Processequipment.RotaryPump
    | RotatingExtruder of Dexpi2.Plant.Processequipment.RotatingExtruder
    | RotatingGrowthAgglomerator of Dexpi2.Plant.Processequipment.RotatingGrowthAgglomerator
    | RotatingPressureAgglomerator of Dexpi2.Plant.Processequipment.RotatingPressureAgglomerator
    | ScrubbingSeparator of Dexpi2.Plant.Processequipment.ScrubbingSeparator
    | SedimentalCentrifuge of Dexpi2.Plant.Processequipment.SedimentalCentrifuge
    | Separator of Dexpi2.Plant.Processequipment.Separator
    | Ship of Dexpi2.Plant.Processequipment.Ship
    | Sieve of Dexpi2.Plant.Processequipment.Sieve
    | Silo of Dexpi2.Plant.Processequipment.Silo
    | SpiralHeatExchanger of Dexpi2.Plant.Processequipment.SpiralHeatExchanger
    | SprayCooler of Dexpi2.Plant.Processequipment.SprayCooler
    | StaticMixer of Dexpi2.Plant.Processequipment.StaticMixer
    | StationarySieve of Dexpi2.Plant.Processequipment.StationarySieve
    | StationaryTransportSystem of Dexpi2.Plant.Processequipment.StationaryTransportSystem
    | SteamGenerator of Dexpi2.Plant.Processequipment.SteamGenerator
    | SteamTurbine of Dexpi2.Plant.Processequipment.SteamTurbine
    | TaggedColumnSection of Dexpi2.Plant.Processequipment.TaggedColumnSection
    | Tank of Dexpi2.Plant.Processequipment.Tank
    | ThinFilmEvaporator of Dexpi2.Plant.Processequipment.ThinFilmEvaporator
    | TransportableContainer of Dexpi2.Plant.Processequipment.TransportableContainer
    | Truck of Dexpi2.Plant.Processequipment.Truck
    | TubularHeatExchanger of Dexpi2.Plant.Processequipment.TubularHeatExchanger
    | Turbine of Dexpi2.Plant.Processequipment.Turbine
    | Vessel of Dexpi2.Plant.Processequipment.Vessel
    | VibratingSieve of Dexpi2.Plant.Processequipment.VibratingSieve
    | WasteGasEmitter of Dexpi2.Plant.Processequipment.WasteGasEmitter
    | Weigher of Dexpi2.Plant.Processequipment.Weigher
    | WetCoolingTower of Dexpi2.Plant.Processequipment.WetCoolingTower

    /// <summary>全部案例（含非叶类），按 C# 类型全名排序。</summary>
    static member All : TaggedPlantItem list =
        [ Agglomerator (new Dexpi2.Plant.Processequipment.Agglomerator())
          Agitator (new Dexpi2.Plant.Processequipment.Agitator())
          AirCoolingSystem (new Dexpi2.Plant.Processequipment.AirCoolingSystem())
          AirEjector (new Dexpi2.Plant.Processequipment.AirEjector())
          AlternatingCurrentGenerator (new Dexpi2.Plant.Processequipment.AlternatingCurrentGenerator())
          AlternatingCurrentMotor (new Dexpi2.Plant.Processequipment.AlternatingCurrentMotor())
          AxialBlower (new Dexpi2.Plant.Processequipment.AxialBlower())
          AxialCompressor (new Dexpi2.Plant.Processequipment.AxialCompressor())
          AxialFan (new Dexpi2.Plant.Processequipment.AxialFan())
          BatchWeigher (new Dexpi2.Plant.Processequipment.BatchWeigher())
          Blower (new Dexpi2.Plant.Processequipment.Blower())
          Boiler (new Dexpi2.Plant.Processequipment.Boiler())
          Burner (new Dexpi2.Plant.Processequipment.Burner())
          CentrifugalBlower (new Dexpi2.Plant.Processequipment.CentrifugalBlower())
          CentrifugalCompressor (new Dexpi2.Plant.Processequipment.CentrifugalCompressor())
          CentrifugalPump (new Dexpi2.Plant.Processequipment.CentrifugalPump())
          Centrifuge (new Dexpi2.Plant.Processequipment.Centrifuge())
          Chimney (new Dexpi2.Plant.Processequipment.Chimney())
          CombustionEngine (new Dexpi2.Plant.Processequipment.CombustionEngine())
          Compressor (new Dexpi2.Plant.Processequipment.Compressor())
          ContinuousWeigher (new Dexpi2.Plant.Processequipment.ContinuousWeigher())
          ConvectionDryer (new Dexpi2.Plant.Processequipment.ConvectionDryer())
          Conveyor (new Dexpi2.Plant.Processequipment.Conveyor())
          CoolingTower (new Dexpi2.Plant.Processequipment.CoolingTower())
          Crusher (new Dexpi2.Plant.Processequipment.Crusher())
          DirectCurrentGenerator (new Dexpi2.Plant.Processequipment.DirectCurrentGenerator())
          DirectCurrentMotor (new Dexpi2.Plant.Processequipment.DirectCurrentMotor())
          DryCoolingTower (new Dexpi2.Plant.Processequipment.DryCoolingTower())
          Dryer (new Dexpi2.Plant.Processequipment.Dryer())
          EjectorPump (new Dexpi2.Plant.Processequipment.EjectorPump())
          ElectricGenerator (new Dexpi2.Plant.Processequipment.ElectricGenerator())
          ElectricHeater (new Dexpi2.Plant.Processequipment.ElectricHeater())
          ElectricalSeparator (new Dexpi2.Plant.Processequipment.ElectricalSeparator())
          Extruder (new Dexpi2.Plant.Processequipment.Extruder())
          Fan (new Dexpi2.Plant.Processequipment.Fan())
          Feeder (new Dexpi2.Plant.Processequipment.Feeder())
          Filter (new Dexpi2.Plant.Processequipment.Filter())
          FilteringCentrifuge (new Dexpi2.Plant.Processequipment.FilteringCentrifuge())
          Flare (new Dexpi2.Plant.Processequipment.Flare())
          ForkliftTruck (new Dexpi2.Plant.Processequipment.ForkliftTruck())
          Furnace (new Dexpi2.Plant.Processequipment.Furnace())
          GasFilter (new Dexpi2.Plant.Processequipment.GasFilter())
          GasTurbine (new Dexpi2.Plant.Processequipment.GasTurbine())
          GravitationalSeparator (new Dexpi2.Plant.Processequipment.GravitationalSeparator())
          Grinder (new Dexpi2.Plant.Processequipment.Grinder())
          HeatExchanger (new Dexpi2.Plant.Processequipment.HeatExchanger())
          HeatedSurfaceDryer (new Dexpi2.Plant.Processequipment.HeatedSurfaceDryer())
          Heater (new Dexpi2.Plant.Processequipment.Heater())
          Kneader (new Dexpi2.Plant.Processequipment.Kneader())
          Lift (new Dexpi2.Plant.Processequipment.Lift())
          LiquidFilter (new Dexpi2.Plant.Processequipment.LiquidFilter())
          LoadingUnloadingSystem (new Dexpi2.Plant.Processequipment.LoadingUnloadingSystem())
          MechanicalSeparator (new Dexpi2.Plant.Processequipment.MechanicalSeparator())
          Mill (new Dexpi2.Plant.Processequipment.Mill())
          Mixer (new Dexpi2.Plant.Processequipment.Mixer())
          MobileTransportSystem (new Dexpi2.Plant.Processequipment.MobileTransportSystem())
          Motor (new Dexpi2.Plant.Processequipment.Motor())
          PackagingSystem (new Dexpi2.Plant.Processequipment.PackagingSystem())
          PlateHeatExchanger (new Dexpi2.Plant.Processequipment.PlateHeatExchanger())
          PressureVessel (new Dexpi2.Plant.Processequipment.PressureVessel())
          ProcessColumn (new Dexpi2.Plant.Processequipment.ProcessColumn())
          Pump (new Dexpi2.Plant.Processequipment.Pump())
          RadialFan (new Dexpi2.Plant.Processequipment.RadialFan())
          RailWaggon (new Dexpi2.Plant.Processequipment.RailWaggon())
          ReciprocatingCompressor (new Dexpi2.Plant.Processequipment.ReciprocatingCompressor())
          ReciprocatingExtruder (new Dexpi2.Plant.Processequipment.ReciprocatingExtruder())
          ReciprocatingPressureAgglomerator (new Dexpi2.Plant.Processequipment.ReciprocatingPressureAgglomerator())
          ReciprocatingPump (new Dexpi2.Plant.Processequipment.ReciprocatingPump())
          RevolvingSieve (new Dexpi2.Plant.Processequipment.RevolvingSieve())
          RotaryCompressor (new Dexpi2.Plant.Processequipment.RotaryCompressor())
          RotaryMixer (new Dexpi2.Plant.Processequipment.RotaryMixer())
          RotaryPump (new Dexpi2.Plant.Processequipment.RotaryPump())
          RotatingExtruder (new Dexpi2.Plant.Processequipment.RotatingExtruder())
          RotatingGrowthAgglomerator (new Dexpi2.Plant.Processequipment.RotatingGrowthAgglomerator())
          RotatingPressureAgglomerator (new Dexpi2.Plant.Processequipment.RotatingPressureAgglomerator())
          ScrubbingSeparator (new Dexpi2.Plant.Processequipment.ScrubbingSeparator())
          SedimentalCentrifuge (new Dexpi2.Plant.Processequipment.SedimentalCentrifuge())
          Separator (new Dexpi2.Plant.Processequipment.Separator())
          Ship (new Dexpi2.Plant.Processequipment.Ship())
          Sieve (new Dexpi2.Plant.Processequipment.Sieve())
          Silo (new Dexpi2.Plant.Processequipment.Silo())
          SpiralHeatExchanger (new Dexpi2.Plant.Processequipment.SpiralHeatExchanger())
          SprayCooler (new Dexpi2.Plant.Processequipment.SprayCooler())
          StaticMixer (new Dexpi2.Plant.Processequipment.StaticMixer())
          StationarySieve (new Dexpi2.Plant.Processequipment.StationarySieve())
          StationaryTransportSystem (new Dexpi2.Plant.Processequipment.StationaryTransportSystem())
          SteamGenerator (new Dexpi2.Plant.Processequipment.SteamGenerator())
          SteamTurbine (new Dexpi2.Plant.Processequipment.SteamTurbine())
          TaggedColumnSection (new Dexpi2.Plant.Processequipment.TaggedColumnSection())
          Tank (new Dexpi2.Plant.Processequipment.Tank())
          ThinFilmEvaporator (new Dexpi2.Plant.Processequipment.ThinFilmEvaporator())
          TransportableContainer (new Dexpi2.Plant.Processequipment.TransportableContainer())
          Truck (new Dexpi2.Plant.Processequipment.Truck())
          TubularHeatExchanger (new Dexpi2.Plant.Processequipment.TubularHeatExchanger())
          Turbine (new Dexpi2.Plant.Processequipment.Turbine())
          Vessel (new Dexpi2.Plant.Processequipment.Vessel())
          VibratingSieve (new Dexpi2.Plant.Processequipment.VibratingSieve())
          WasteGasEmitter (new Dexpi2.Plant.Processequipment.WasteGasEmitter())
          Weigher (new Dexpi2.Plant.Processequipment.Weigher())
          WetCoolingTower (new Dexpi2.Plant.Processequipment.WetCoolingTower())
          ]
