// <auto-generated>
// 可区分联合：Dexpi2.Plant.Processequipment.TaggedPlantItem 的所有非抽象派生类型（含非叶类）。
// 每个案例荷载对应的 C# 类型（System.Type），类型来自 Dexpi2.CSharp 程序集。
// 生成方式：dotnet fsi FSharp.DEXPI2/tools/generate-tagged-plant-item-union.fsx
// 数据来源：Dexpi2.CSharp.Generator/input/*.hpp 中 "[flattened; bases inlined: ...]" 直系基类注释。
// </auto-generated>

namespace FSharp.DEXPI2.Plant.ProcessEquipment

open System
open Dexpi2.Plant.Processequipment

/// <summary>可区分联合：TaggedPlantItem 的所有非抽象派生类型（含非叶类）。每个案例荷载对应的 C# 类型。</summary>
type TaggedPlantItemUnion =
    | AgglomeratorCase of Type
    | AgitatorCase of Type
    | AirCoolingSystemCase of Type
    | AirEjectorCase of Type
    | AlternatingCurrentGeneratorCase of Type
    | AlternatingCurrentMotorCase of Type
    | AxialBlowerCase of Type
    | AxialCompressorCase of Type
    | AxialFanCase of Type
    | BatchWeigherCase of Type
    | BlowerCase of Type
    | BoilerCase of Type
    | BurnerCase of Type
    | CentrifugalBlowerCase of Type
    | CentrifugalCompressorCase of Type
    | CentrifugalPumpCase of Type
    | CentrifugeCase of Type
    | ChimneyCase of Type
    | CombustionEngineCase of Type
    | CompressorCase of Type
    | ContinuousWeigherCase of Type
    | ConvectionDryerCase of Type
    | ConveyorCase of Type
    | CoolingTowerCase of Type
    | CrusherCase of Type
    | DirectCurrentGeneratorCase of Type
    | DirectCurrentMotorCase of Type
    | DryCoolingTowerCase of Type
    | DryerCase of Type
    | EjectorPumpCase of Type
    | ElectricGeneratorCase of Type
    | ElectricHeaterCase of Type
    | ElectricalSeparatorCase of Type
    | ExtruderCase of Type
    | FanCase of Type
    | FeederCase of Type
    | FilterCase of Type
    | FilteringCentrifugeCase of Type
    | FlareCase of Type
    | ForkliftTruckCase of Type
    | FurnaceCase of Type
    | GasFilterCase of Type
    | GasTurbineCase of Type
    | GravitationalSeparatorCase of Type
    | GrinderCase of Type
    | HeatExchangerCase of Type
    | HeatedSurfaceDryerCase of Type
    | HeaterCase of Type
    | KneaderCase of Type
    | LiftCase of Type
    | LiquidFilterCase of Type
    | LoadingUnloadingSystemCase of Type
    | MechanicalSeparatorCase of Type
    | MillCase of Type
    | MixerCase of Type
    | MobileTransportSystemCase of Type
    | MotorCase of Type
    | PackagingSystemCase of Type
    | PlateHeatExchangerCase of Type
    | PressureVesselCase of Type
    | ProcessColumnCase of Type
    | PumpCase of Type
    | RadialFanCase of Type
    | RailWaggonCase of Type
    | ReciprocatingCompressorCase of Type
    | ReciprocatingExtruderCase of Type
    | ReciprocatingPressureAgglomeratorCase of Type
    | ReciprocatingPumpCase of Type
    | RevolvingSieveCase of Type
    | RotaryCompressorCase of Type
    | RotaryMixerCase of Type
    | RotaryPumpCase of Type
    | RotatingExtruderCase of Type
    | RotatingGrowthAgglomeratorCase of Type
    | RotatingPressureAgglomeratorCase of Type
    | ScrubbingSeparatorCase of Type
    | SedimentalCentrifugeCase of Type
    | SeparatorCase of Type
    | ShipCase of Type
    | SieveCase of Type
    | SiloCase of Type
    | SpiralHeatExchangerCase of Type
    | SprayCoolerCase of Type
    | StaticMixerCase of Type
    | StationarySieveCase of Type
    | StationaryTransportSystemCase of Type
    | SteamGeneratorCase of Type
    | SteamTurbineCase of Type
    | TaggedColumnSectionCase of Type
    | TankCase of Type
    | ThinFilmEvaporatorCase of Type
    | TransportableContainerCase of Type
    | TruckCase of Type
    | TubularHeatExchangerCase of Type
    | TurbineCase of Type
    | VesselCase of Type
    | VibratingSieveCase of Type
    | WasteGasEmitterCase of Type
    | WeigherCase of Type
    | WetCoolingTowerCase of Type

    /// <summary>全部案例（含非叶类），按 C# 类型全名排序。</summary>
    static member All : TaggedPlantItemUnion list =
        [ AgglomeratorCase typeof<Agglomerator>
          AgitatorCase typeof<Agitator>
          AirCoolingSystemCase typeof<AirCoolingSystem>
          AirEjectorCase typeof<AirEjector>
          AlternatingCurrentGeneratorCase typeof<AlternatingCurrentGenerator>
          AlternatingCurrentMotorCase typeof<AlternatingCurrentMotor>
          AxialBlowerCase typeof<AxialBlower>
          AxialCompressorCase typeof<AxialCompressor>
          AxialFanCase typeof<AxialFan>
          BatchWeigherCase typeof<BatchWeigher>
          BlowerCase typeof<Blower>
          BoilerCase typeof<Boiler>
          BurnerCase typeof<Burner>
          CentrifugalBlowerCase typeof<CentrifugalBlower>
          CentrifugalCompressorCase typeof<CentrifugalCompressor>
          CentrifugalPumpCase typeof<CentrifugalPump>
          CentrifugeCase typeof<Centrifuge>
          ChimneyCase typeof<Chimney>
          CombustionEngineCase typeof<CombustionEngine>
          CompressorCase typeof<Compressor>
          ContinuousWeigherCase typeof<ContinuousWeigher>
          ConvectionDryerCase typeof<ConvectionDryer>
          ConveyorCase typeof<Conveyor>
          CoolingTowerCase typeof<CoolingTower>
          CrusherCase typeof<Crusher>
          DirectCurrentGeneratorCase typeof<DirectCurrentGenerator>
          DirectCurrentMotorCase typeof<DirectCurrentMotor>
          DryCoolingTowerCase typeof<DryCoolingTower>
          DryerCase typeof<Dryer>
          EjectorPumpCase typeof<EjectorPump>
          ElectricGeneratorCase typeof<ElectricGenerator>
          ElectricHeaterCase typeof<ElectricHeater>
          ElectricalSeparatorCase typeof<ElectricalSeparator>
          ExtruderCase typeof<Extruder>
          FanCase typeof<Fan>
          FeederCase typeof<Feeder>
          FilterCase typeof<Filter>
          FilteringCentrifugeCase typeof<FilteringCentrifuge>
          FlareCase typeof<Flare>
          ForkliftTruckCase typeof<ForkliftTruck>
          FurnaceCase typeof<Furnace>
          GasFilterCase typeof<GasFilter>
          GasTurbineCase typeof<GasTurbine>
          GravitationalSeparatorCase typeof<GravitationalSeparator>
          GrinderCase typeof<Grinder>
          HeatExchangerCase typeof<HeatExchanger>
          HeatedSurfaceDryerCase typeof<HeatedSurfaceDryer>
          HeaterCase typeof<Heater>
          KneaderCase typeof<Kneader>
          LiftCase typeof<Lift>
          LiquidFilterCase typeof<LiquidFilter>
          LoadingUnloadingSystemCase typeof<LoadingUnloadingSystem>
          MechanicalSeparatorCase typeof<MechanicalSeparator>
          MillCase typeof<Mill>
          MixerCase typeof<Mixer>
          MobileTransportSystemCase typeof<MobileTransportSystem>
          MotorCase typeof<Motor>
          PackagingSystemCase typeof<PackagingSystem>
          PlateHeatExchangerCase typeof<PlateHeatExchanger>
          PressureVesselCase typeof<PressureVessel>
          ProcessColumnCase typeof<ProcessColumn>
          PumpCase typeof<Pump>
          RadialFanCase typeof<RadialFan>
          RailWaggonCase typeof<RailWaggon>
          ReciprocatingCompressorCase typeof<ReciprocatingCompressor>
          ReciprocatingExtruderCase typeof<ReciprocatingExtruder>
          ReciprocatingPressureAgglomeratorCase typeof<ReciprocatingPressureAgglomerator>
          ReciprocatingPumpCase typeof<ReciprocatingPump>
          RevolvingSieveCase typeof<RevolvingSieve>
          RotaryCompressorCase typeof<RotaryCompressor>
          RotaryMixerCase typeof<RotaryMixer>
          RotaryPumpCase typeof<RotaryPump>
          RotatingExtruderCase typeof<RotatingExtruder>
          RotatingGrowthAgglomeratorCase typeof<RotatingGrowthAgglomerator>
          RotatingPressureAgglomeratorCase typeof<RotatingPressureAgglomerator>
          ScrubbingSeparatorCase typeof<ScrubbingSeparator>
          SedimentalCentrifugeCase typeof<SedimentalCentrifuge>
          SeparatorCase typeof<Separator>
          ShipCase typeof<Ship>
          SieveCase typeof<Sieve>
          SiloCase typeof<Silo>
          SpiralHeatExchangerCase typeof<SpiralHeatExchanger>
          SprayCoolerCase typeof<SprayCooler>
          StaticMixerCase typeof<StaticMixer>
          StationarySieveCase typeof<StationarySieve>
          StationaryTransportSystemCase typeof<StationaryTransportSystem>
          SteamGeneratorCase typeof<SteamGenerator>
          SteamTurbineCase typeof<SteamTurbine>
          TaggedColumnSectionCase typeof<TaggedColumnSection>
          TankCase typeof<Tank>
          ThinFilmEvaporatorCase typeof<ThinFilmEvaporator>
          TransportableContainerCase typeof<TransportableContainer>
          TruckCase typeof<Truck>
          TubularHeatExchangerCase typeof<TubularHeatExchanger>
          TurbineCase typeof<Turbine>
          VesselCase typeof<Vessel>
          VibratingSieveCase typeof<VibratingSieve>
          WasteGasEmitterCase typeof<WasteGasEmitter>
          WeigherCase typeof<Weigher>
          WetCoolingTowerCase typeof<WetCoolingTower>
          ]
